### ISSUE TITLE
Respawn Anchors

### ISSUE THREAD

**Issue by FunneTetraSystem** [nekomaster1000/Infernal-Expansion#118]
**Describe the bug**
You can't set your spawn in the nether as trying to use glowstone dust on an anchor doesn't work

**To Reproduce**
Grab a respawn anchor and tried to click Glowstone dust on it

**Expected behavior**
I expected the respawn anchor to charge up and set my spawn

**Version Information**
 - Operating System: MacOS
 - Mod Version: 2.0.0 Beta release
 - Minecraft Version: 1.16.5
 - Forge Version: I think 1.16.5? Forge versions confuse me
 - Other mods that were running when the crash happened:

**Comment by SwanX1** [comment]
Not a bug, this behaviour isn't changed by Infernal Expansion, you're supposed to use Glowstone Blocks instead of Dust
