### ISSUE TITLE
Crash on launch with more waterlogging installed

### ISSUE THREAD

**Issue by Direbat** [nekomaster1000/Infernal-Expansion#129]
**Describe the bug**
When launching infernal expansion along with more waterlogging the game crashes, however I am not sure if this could be fixed on your side please tell me if it can be fixed by you.

**To Reproduce**
1. install infernal expansion 2.00 beta 3
2. install more waterlogging 1.4
3. launch Minecraft

**Expected behavior**
No crash

**Screenshots**
![2021-05-08_23 01 25](https://user-images.githubusercontent.com/74643395/117548217-5f248300-b051-11eb-90b2-5e84bff328c8.png)

**Version Information**
 - Operating System: (not sure what you mean by this) windows?
 - Mod Version: 2.00 beta 3
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.0
 - Other mods that were running when the crash happened: more waterlogging 1.4

**Additional context**
crash log
[latest.log](https://github.com/infernalexp/Infernal-Expansion/files/6446271/latest.log)

**Comment by Dariensg** [comment]
MoreWaterlogging would have to fix this on their side. The dev knows this and isn't currently supporting that mod. We've already marked our mod as incompatible with theirs. We're sorry for any inconvenience.

**Comment by Direbat** [comment]
Understood, thank you for clarifying
