### ISSUE TITLE
Spawn Rate Problem

### ISSUE THREAD

**Issue by nekomaster1000** [nekomaster1000/Infernal-Expansion#13]
Despite having their spawn weight in the biome file set to 2, Blindsights spawn constantly. Inversely, Glowsquitos barely spawn at all despite having a spawn weight of 100.

**Comment by ihaveacrushonjaidenanimations2068** [comment]
I believe I know what's happening; The spawnrate numbers may work inversely, as in lower=more common  and higher=rarer
Hope that helps ig

**Comment by SwanX1** [comment]
Is this still an issue? If not, please close it, @nekomaster1000.
