### ISSUE TITLE
some Sounds cut off in Crimson Forest + Possibly other biomes

### ISSUE THREAD

**Issue by Inonedn** [nekomaster1000/Infernal-Expansion#138]
**Describe the bug**
When you spend enough time in the Nether's Crimson Forest, sounds start to cut out

**To Reproduce**
Spend some time in the Crimson Forest and do stuff like a constant running composter

**Expected behavior**
the sounds don't cut off
**Screenshots**

**Version Information**
 - Operating System: All
 - Mod Version: Beta 2.0.0-3
 - Minecraft Version: 1.16.5
 - Forge Version: Latest

**Comment by Dariensg** [comment]
Could not reproduce this issue
