### ISSUE TITLE
[1.16.4] Latest commit breaks mob rendering

### ISSUE THREAD

**Issue by ihaveacrushonjaidenanimations2068** [nekomaster1000/Infernal-Expansion#14]
While testing a potential fix for #13 in my dev environment, I noticed every mob turned a solid yellow.
Now IDK if it was this mod's fault but just thought I'd put it here
![2021-01-15_16 28 47](https://user-images.githubusercontent.com/43296868/104700221-ca6ae200-574e-11eb-88aa-c552180469cd.png)

**Comment by reetamb** [comment]
there is a work in progress effect that gives mobs a yellow outline like glowing, however it's not done yet so in a dev environment you will have that happen. it will get fixed before the release though

**Comment by caelwarner** [comment]
I'm gonna create and add a dev build tag for issues like this one

**Comment by SwanX1** [comment]
Luminous test is moved to another branch,
