### ISSUE TITLE
[Suggestion] Blindsights Problems and Changes

### ISSUE THREAD

**Issue by FunneTetraSystem** [nekomaster1000/Infernal-Expansion#144]
-They usually stay out of range of most weapons thus rendering whips and hoes the only things that are effective

-They have a wide detection range which makes a lot of them gang up on you

-Their damage is too high for how common they are

One of the changes I would make to the blindsight to make them less annoying are

-Smaller detection range

-Blindsights don’t detect players when standing still so if you’re being chased by Blindsights you can stand still and they’ll ignore you giving you opportunities to heal

-Sneaking lessens the detection more but they can still detect you while sneaking if you’re too close

**Comment by Dariensg** [comment]
Some of these changes, along with some slightly different, but similar, ones were made in the linked Pull Request. This should fix this and make the Blindsight experience a bit better. Closing now.
