### ISSUE TITLE
Glowstone Canyon doesn't generate in pre-existing worlds

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [nekomaster1000/Infernal-Expansion#161]
**Describe the Bug:**
I noticed that after adding this mod to my custom modpack recently that I couldn't find the Glowstone Canyon in the nether. After some investigating I found that if I started a new world then the Glowstone Canyon generated correctly, whereas if I tried to add this mod to an existing world (i.e one that existed before installing Infernal Expansion) then the biome was nowhere to be found, and the /locatebiome command couldn't locate it.

**How to Reproduce:**
1. Start a new world without Infernal Expansion and enter the nether.
2. Close the game and Install infernal expansion (Beta version) 
3. Try to locate the Glowstone Canyon.
4. You will find that the biome is nowhere to be found and the /locatebiome command can't locate it.

**Expected Behavior:**
The Glowstone Canyon would generate and get added to nether dimensions in worlds that existed before adding Infernal Expansion.

**Screenshots:**
![2021-07-15_14 53 33](https://user-images.githubusercontent.com/64381954/125800562-f93e2a5d-3f88-4fb4-912b-3b6ef24dd323.png)

**Version Information:**
 - Operating System: Windows 10
 - Mod Version: 2.0.0 Beta 6
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.33
 - Other mods that were running when the crash happened: None (Issue occurs without any other mods installed.)

**Additional Context:**
I have found that this issue still occurs without any other mods installed, so there are no mod conflicts causing this, it seems to be a problem with this mod and/or Vanilla Minecraft.

**Comment by Dariensg** [comment]
Unfortunately, this is an issue with how Forge handles modded Nether biomes. That is to say, it basically doesn't. Until Forge fixes this, I don't think it's possible to get our biomes to spawn in an existing world created before IE was installed. Just for some peace of mind, we aren't the only ones with this issue. I tested this the same way with Oh the Biomes You'll Go, and it had the same issues. The Nether biomes would not generate in an existing world, but the Overworld ones did. Sadly, this has to be marked as "Won't Fix" until Forge adds a Nether biome hook. Sorry for any inconvenience this may cause!

**Comment by The-Bernician-Lamb** [comment]
I see, That's disappointing but I understand. Thanks for your help. I look forward to seeing what you add to this mod in the future!

**Comment by Wedge1453** [comment]
I tested deleting the nether dimension folder (DIM-1) and it still doesn't generate, unfortunatly

**Comment by Dariensg** [comment]
As stated previously, this isn't an issue with the mod. It is an issue with how Forge handles Nether Biomes and cannot be fixed at this time. This issue should persist across any Nether Biomes from any mod. I've tested this with Oh The Biomes You'll Go and had the exact same results.
