### ISSUE TITLE
Silk Touch not applying to Dullstone

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#163]
**Describe the Bug:**
Dullstone does not drop itself when mined with a Silk Touch Pickaxe, instead dropping dullrocks
**How to Reproduce:**
Step one: Get a Silk Touch Pickaxe
Step two: Mine Dullstone

**Expected Behavior:**
Dullstone should drop itself when mined with a Silk Touch Pickaxe

**Version Information:**
 - Mod Version: 2.0.0 Beta 6

**Comment by SwanX1** [comment]
Fixed by 81aadb61a3151f2cc6949ef9fbde655473879e5a
