### ISSUE TITLE
Unstable glowstone canyon sand should give the player a small warning before falling

### ISSUE THREAD

**Issue by Ramoddi** [nekomaster1000/Infernal-Expansion#164]
**Describe the addition:**
Warning for the unstable sand

**Additional Context:**
One of the rules of Minecraft is that the player should be at fault for dying. I think falling to their deaths, often in lava, just by walking should not be a thing. I would love this feature if the sand glimmers and makes a sound or something, to warn the player of the danger. This would make the feature more fun and fair! And make it easier to clutch, which could be satisfying yet andrealin filled.

**Comment by Dariensg** [comment]
I know what you mean, before we continue with this discussion, I do want to point out that the falling blocks have a different (and usually darker) texture than the other sand, which is a fairly good visual cue to avoid it.

That said, do you still think that isn't enough of a warning?

**Comment by Ramoddi** [comment]
I plopped straight into lava with no idea what happened. Also when going around in creative I did not notice the difference, there is just som much new fascinating stuff to look at that I do not notice the different texture. I think this would take at least once, or multiple falls before a player learns the dangers. The problem I feel, is that I cannot save myself and I ended up confused instead of feeling like it was my fault. I love the idea of the feature though! And think with a small warning for the player, it could be one of the coolest features I have seen in modded biomes

**Comment by Dariensg** [comment]
The other interesting thing is that I don't believe those should ever drop into lava. They should always have a solid bottom and not be a large enough fall to kill at full health. We will have to look into that and maybe think about some sort of sensory warning!

**Comment by SwanX1** [comment]
Please continue discussion in a discussion: https://github.com/infernalexp/Infernal-Expansion/discussions/165
