### ISSUE TITLE
Crash Server when using new version

### ISSUE THREAD

**Issue by huyhhuy1410** [nekomaster1000/Infernal-Expansion#169]
**Describe the Bug:**
Crash when use new beta version of Infernal Expansion Mod on my Forge server !

**How to Reproduce:**
Step 1: Delete old mod file and replace with new beta mod file.
Step 2: Start the server.
Step 3: Crash server when startup server.

**Expected Behavior:**
I was expecting everything to be normal.

**Screenshots:**
![image](https://user-images.githubusercontent.com/86774570/125907505-c31a9557-995c-45bf-a0e0-9b66ccf698af.png)
https://pastebin.com/x8iEntPV

**Version Information:**
 - Mod Version: Infernal Expansion Beta 2.0.0-6
 - Minecraft Version: 1.16.5
 - Other mods that were running when the crash happened:

![image](https://user-images.githubusercontent.com/86774570/125907731-dd3e306a-4390-4d92-b31e-1f5c4f87d132.png)
![image](https://user-images.githubusercontent.com/86774570/125907780-0d596d03-2f11-4cd4-a846-8e85efc3c141.png)
![image](https://user-images.githubusercontent.com/86774570/125907804-e0210f85-89d3-4fe5-8384-795a6f308172.png)

**Comment by Dariensg** [comment]
I was looking through your modlist and noticed that you have Infernal Expansion Version 1.3 installed. Are you trying to run a server with both the old release and the new beta installed at the same time?
Also, Is this a normal server or are you running it with something like Mohist?

**Comment by huyhhuy1410** [comment]
> I was looking through your modlist and noticed that you have Infernal Expansion Version 1.3 installed. Are you trying to run a server with both the old release and the new beta installed at the same time?
> Also, Is this a normal server or are you running it with something like Mohist?

The Infernal Expansion Version 1.3 file in the picture was from the old folder before I installed new beta file. I removed that old file when I installed the new one. So i've not tried to run with both files.
Yeah, I'm using Mohist !

**Comment by Dariensg** [comment]
Ok. This is a problem with Mohist. See Issue #158. I believe they are working on a solution to it, but this is on their side and there's nothing we can do. https://github.com/MohistMC/Mohist/issues/1570 This is the issue where it is discussed. It appears they resolved it, so you may need to download a new version. Closing since this isn't on our side and is a duplicate issue.
