### ISSUE TITLE
Turn off light emission for "Luminous" effect

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#172]
**Describe the addition:**
Since the light from the "Luminous" effect can still cause lag, it should have an option to be disabled for lower-end computers.

**Comment by Dariensg** [comment]
This is definitely something we will take into account. Have you had issues with performance due to Luminous? I'm just curious because we tried to write the code initially so that it shouldn't be too system stressful, so it would be good to know if people really are experiencing issues with it.

**Comment by Dariensg** [comment]
I'll add that I was told that the "Luminous Refresh Rate" config should actually do sort of what you're looking for. If you turn that up, it will be less resource intensive and should help with any lag you will face. It's a good way to keep the experience of Luminous while still reducing lag and helping with lower-end systems! Let me know if that doesn't help.

**Comment by neoNoteCoder** [comment]
> Have you had issues with performance due to Luminous? I'm just curious because we tried to write the code initially so that it shouldn't be too system stressful.

With other mods, (about fifteen it starts becoming a problem) yes. However, with the mod on its own, it's not too stressful on my gameplay.

**Comment by Dariensg** [comment]
Have you adjusted the Refresh Rate value to test higher values and see if it runs better?

**Comment by neoNoteCoder** [comment]
That seems to do the trick, thanks!

**Comment by Dariensg** [comment]
Sounds good! Closing the issue.
