### ISSUE TITLE
Ascus bombs

### ISSUE THREAD

**Issue by Direbat** [nekomaster1000/Infernal-Expansion#175]
**Describe the addition:**
Ascus bombs should be stackable to 16 similar to enderpearls not only would this make them easier to use but it would also mean that they would not clog up your inventory

**Screenshots:**
![2021-07-17_23 19 47](https://user-images.githubusercontent.com/74643395/126057773-9a78f9d9-ae5d-4bb4-97a0-0fa174a1be78.png)
killing one shroomloin with looting 3 clogs up 5 inventory slots.

**Comment by Direbat** [comment]
Also, I am loving the new sounds for the ascus bombs my thanks to the person that made it

**Comment by Dariensg** [comment]
Fixed by Commit 285f76c86129b1ea271fe68073f52dc4fb7e64f0
