### ISSUE TITLE
Game sometimes crashes when Skeletons attack something with a melee weapon in the nether

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [nekomaster1000/Infernal-Expansion#177]
**Describe the Bug:**
I recently added Infernal Expansion to my modpack and since then I've been getting these crashes whenever I've been in the nether. After looking at the crash report it seems to be caused by something related to the skeleton AI changes made by this mod. This crash only started happening when I added Infernal expansion to my modpack. 

**How to Reproduce:**
1. Load into a world with infernal expansion and the skeleton AI changes enabled.
2. Go to the nether.
3. Spawn some skeletons and piglins or whatever else skeletons are aggressive towards that's added by the mod.
4. After a bit of time of the mobs fighting the game crashes with the crash report attached below.

**Expected Behavior:**
The game would not crash whenever skeletons fought a mob in the nether.

**Version Information:**
 - Operating System: Windows 10
 - Mod Version: 2.0.0 beta 7
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.62
 - Other mods that were running when the crash happened: (See crash report)

**Additional Context:**
Crash report: https://gist.github.com/NJL5390/26b49fde47ea8ce9a1be1a49eef8ccf7

**EDIT**: I have since been able to reproduce this issue with only Infernal Expansion. It only seems to occur if the skeletons have melee weapons though, such as swords or axes. If you need to summon one in for testing purposes use this command:

/summon minecraft:skeleton ~ ~ ~ {HandItems:[{Count:1,id:"minecraft:diamond_axe"},{}]}

**Comment by SwanX1** [comment]
I noticed you have the Big Brain mod installed, among others. Please try to remove Infernal Expansion to see if the issue persists.

**Comment by The-Bernician-Lamb** [comment]
This issue doesn't occur without Infernal Expansion. Like I said in the initial description, this issue only started happening when I installed Infernal Expansion. I'll see if I can reproduce it with only Infernal Expansion installed.

**Comment by Dariensg** [comment]
I've done a bit of testing. So far, I've been unable to recreate the issue with IE alone, Big Brain alone, or the both of them together. Looking at the crash report, the error comes from Big Brain, but that means there should be a way to replicate it with Big Brain and so far I've been unable to do that. Let me know if you find a consistent way to replicate it!

**Comment by The-Bernician-Lamb** [comment]
I've had the same results from my testing. I'll let you know if I find a way to reproduce it more consistently. I'm thinking it's probably a combination of Big brain, IE and some other mod causing this.

**Comment by The-Bernician-Lamb** [comment]
So I have been able to reproduce this issue with only Big Brain, IE and Sapience. This crash only started occurring when I gave the skeletons melee weapons (e.g swords and axes). 

Crash Report: https://gist.github.com/NJL5390/26b49fde47ea8ce9a1be1a49eef8ccf7

To give them melee weapons I've been using this command to summon them with melee weapons:

/summon minecraft:skeleton ~ ~ ~ {HandItems:[{Count:1,id:"minecraft:diamond_axe"},{}]}

**Comment by Dariensg** [comment]
Interesting! I have some other work things (not IE related) to do today, but I'm going to proceed with some testing later involving every possible combination of those three mods using skeletons with melee weapons. I'm curious if it's reproducible with Big Brain alone, Big Brain with Sapience, IE with Sapience, Sapience alone, etc.

**Comment by The-Bernician-Lamb** [comment]
So, I've now been able to reproduce this with only IE.

https://gist.github.com/NJL5390/26b49fde47ea8ce9a1be1a49eef8ccf7

Seems to be related to skeletons using melee weapons, as it only starts happening after I spawn in skeletons with melee weapons. And having them fight some stuff, this was in a nether wastes biome in case that has anything to do with it.

**Comment by Dariensg** [comment]
Ah thank you! We actually think this might be similar to an older bug we fixed a while ago with Spiders, so it hopefully shouldn't take us too long to fix! Thank you for all the information and testing! It's been super helpful.

**Comment by Dariensg** [comment]
Quick Update: Things are taking a bit longer than I had hoped, but I want to thank you. It turns out the old bug that I mentioned never actually got fixed due to a miscommunication, so I’m working on tracking down the source of the issue. Several of our coders are currently on vacation or busy with other projects, so we’re down a few people right now, but hopefully I’ll be able to crack this issue soon!

**Comment by The-Bernician-Lamb** [comment]
No problem! I always try to help out in whatever way I can, after all it only helps the issue get fixed faster!
