### ISSUE TITLE
Cannot go to Nether

### ISSUE THREAD

**Issue by Casualmira** [nekomaster1000/Infernal-Expansion#18]
I cannot use /NTP or a vanilla portal to travel to the nether. I can give a list of mods, or send my mod pack if needed - it is custom, quite light. 

NTP command throws an error (am OP'd), Portal does light, but standing inside gives the usual effect but does not teleport to dimension. 

Sorry I can't provide more information right now, I'm not sure what is useful to you.

**Comment by SwanX1** [comment]
Are you sure it's Infernal Expansion causing this? If you could send a log that would be great too. Put the files in the `logs` folder in a pastebin (I recommend [paste.gg](https://paste.gg/)) and reply with the paste link.
If you could also provide a modlist, and some information about the system you're running on (32 or 64-bit, ram and processor, os), that would be helpful.

**Comment by Casualmira** [comment]
Naturally, no I'm not certain - but it's the biggest portion of code which will affect the way the nether works, so I'm here first. But I suppose it could also be another Dim mod, too.

I will be disabling mods and repackaging everything to see if I can narrow it down, if i get time this weekend. 

64-bit Win 10, on Ryzen 3600X, 32GB ram, 1070 TI. Shouldn't really have any influence on the issue, surely?

https://paste.gg/p/anonymous/49e0528c2ff7473185c89d5e5f219ab5

Above are the 2 files i can access, am i supposed to be able to access the .gz?

**Comment by SwanX1** [comment]
Can you provide a modlist, so I can try to reproduce the issue?

**Comment by Casualmira** [comment]
I can. it will have to be tonight... or I can ship you the zip to install
it?

**Comment by Casualmira** [comment]
Mod list inc. versions

Aquaculture-1.16.4-2.1.11.jar
ars_nouveau-1.16.4-1.10.6.jar
BiomesOPlenty-1.16.4-13.0.0.427-universal.jar
BotanyPots-1.16.4-6.0.7.jar
chiselsandbits-0.2.8-RELEASE.jar
curios-forge-1.16.4-4.0.3.3.jar
ftb-chunks-1604.2.2.57.jar
ftb-gui-library-1604.1.1.26.jar
forge-1.16.4-geckolib-3.0.0.jar
JustEnoughResources-1.16.4-0.12.0.103.jar
Mekanism-1.16.4-10.0.18.445.jar
MekanismAdditions-1.16.4-10.0.18.445.jar
MekanismGenerators-1.16.4-10.0.18.445.jar
MekanismTools-1.16.4-10.0.18.445.jar
OresAboveDiamonds-1.16.4-v6.3.1.jar
pamhc2foodcore-1.16.3-1.0.0.jar
performant-1.16.2-4-3.29m.jar
Placebo-1.16.3-4.3.3.jar
Quark-r2.4-291.jar
ScalingHealth-1.16.4-4.0.2+2.jar
SilentGear-1.16.3-2.4.11+200.jar
SilentLib-1.16.3-4.9.0+63.jar
SilentGems-1.16.3-3.7.7+110.jar
TheAbyss 1.0.7 1.16.4.jar
Vampirism-1.16.4-1.7.1.jar
veinmining-forge-1.16.4-0.4.jar
Xaeros_Minimap_20.30.1_Forge_1.16.4.jar
xptome-1.16.2-v1.1.6.jar
abnormals_core-1.16.4-3.0.6.jar
mining_dimension-1.16.4-1.0.3.jar
Apotheosis-1.16.3-4.4.1.jar
AutoRegLib-1.6-47.jar
BasicNetherOres-1.16.4-5.4.0.jar
bspawncontrol_1.16.4-1.1.jar
Bookshelf-1.16.4-9.3.25.jar
Clumps-6.0.0.13.jar
collective-1.16.4-1.53.jar
CookingForBlockheads_1.16.3-9.2.2.jar
corpse-1.16.4-1.0.5.jar
despawningeggshatch_1.16.4-2.0.jar
DungeonCrawl-1.16.3-2.2.4.jar
ftb-essentials-1604.1.0.13.jar
gaiadimension-1.16.4-1.3.1.jar
infernal-expansion-forge-1.2.0.jar
ironchest-1.16.4-11.2.10.jar
jei-1.16.4-7.6.1.65.jar
moredragoneggs-1.4.jar
no-nitwits-1.16.4-1.0.0.jar
pamhc2crops-1.16.3-1.0.1.jar
pamhc2foodextended-1.16.3-1.0.0.jar
pamhc2trees-1.16.3-1.0.0.jar
Patchouli-1.16.4-48.jar
ResourcefulBees1.16.3-1.16.4-0.5.8b.jar
SpawnerFix-1.16.2-1.0.0.2.jar
endergetic-1.16.4-3.0.0.jar
kingvillager-1.6.1.jar
OuterEnd-0.2.3.jar
tnt-yeeter-1.16.4-1.2.0.jar
toolleveling-1.16.2-1.1.1.jar
towers_of_the_wild-1.16.4-2.0.1.jar
valhelsia_structures-16.0.5.jar
WAWLA-1.16.4-7.0.2.jar
Waystones_1.16.3-7.3.1.jar

**Comment by caelwarner** [comment]
Thanks for your issue. However, we haven't been able to recreate this bug. Hopefully newer versions of Infernal Expansion and the mods you have listed here will fix the issue.
