### ISSUE TITLE
Enhanced Mushrooms compatibility

### ISSUE THREAD

**Issue by Pet-Slime** [nekomaster1000/Infernal-Expansion#180]
**Describe the addition:**

Compatability between Infernal expansion and another vanilla plus style mod: enhanced mushrooms. enhanced mushrooms replace mushroom stems with wood-like mushroom stems like those from crimson and warped fungus in the nether. It's kind of jarring if you have both mods installed and run into regular mushroom stems when going for planks from enhanced mushrooms.

Below would be the suggested code/change (at least the initial, there would be a little bit more work) under 

Infernal-Expansion/src/main/java/com/nekomaster1000/infernalexp/world/gen/features/HangingGiantBrownMushroomFeature.java /

```java
// Generate stem
for (int y = 0; y <= size; y++) {
    if (ModList.get().isLoaded("enhanced_mushrooms")) {
        world.setBlockState(pos.down(y), EMBlocks.BROWN_MUSHROOM_STEM.get().getDefaultState(), 2);
    } else {
        world.setBlockState(pos.down(y), Blocks.MUSHROOM_STEM.getDefaultState(), 2);
    }
}
```
**Screenshots:**
https://i.imgur.com/Ff5lSv6.png

**Comment by Dariensg** [comment]
PR is opened and awaiting review! Thanks for the code base! It was a good place to start. We already have some compat utils in place, so it was even a little easier! Should be merged probably within 24 hours and will be in the next beta release.
