### ISSUE TITLE
glowdust sandstone texture issue

### ISSUE THREAD

**Issue by Wedge1453** [nekomaster1000/Infernal-Expansion#184]
infernal-expansion-2.0.0-beta.7.jar

![2021-07-19_19 10 33](https://user-images.githubusercontent.com/76813383/126358734-e27fb1c3-62f9-4edf-a682-e84212bda120.png)

**Comment by Dariensg** [comment]
This issue isn't our mod. The block you're looking at is from a mod called Lepton.
