### ISSUE TITLE
Blindsight whip can be enchanted with any enchantment.

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#186]
**Describe the Bug:**
Any enchantment can be applied to the whip, such as Frost Walker, Lure, Loyalty, etc.

**How to Reproduce:**
Use an enchanting book that would strictly apply to armour or a fishing rod in an anvil.

**Expected Behavior:**
Armour, bow, trident and fishing rod specific books should not be able to enchant the whip.

**Screenshots:**
![image](https://user-images.githubusercontent.com/49106149/126404490-bca5958d-1c26-41f4-ab7d-9cc75817fdc2.png)

**Version Information:**
- Operating System: Windows
- Mod Version: 2.0.0. Beta 7
- Minecraft Version: 1.16.5
- Forge Version: 1.16.5-forge-36.1.0

**Additional Context:**
Enchanting a whip via an enchanting table does not apply enchantments that are specific to other tools.
The incorrect book enchantments do not have an effect on the tool.

**Comment by Dariensg** [comment]
As weird as this sounds, this is a Vanilla mechanic. In Creative, you can apply any enchantment to any tool. We tested on complete Vanilla instances of Minecraft. In Survival, the right enchantments are limited and it works as intended. Strangely, this really is Works as Intended, so I will be closing this issue.
