### ISSUE TITLE
No config file, empty config file

### ISSUE THREAD

**Issue by SaphieNyako** [nekomaster1000/Infernal-Expansion#19]
Hello!

We are currently using 1.2 on the server.
We're having some issues with creatures spawning, cause of the many creatures in the nether there arent enough enderman, so Im hoping to lower some of the spawns.

Issue: There is no config file, or atleast the config file that does excists is empty.

**Comment by SwanX1** [comment]
Hi! You should probably upgrade your mod version to 1.3. The server-side configs, like spawn rates and mob interactions, are available in your world folder: `saves/<world>/serverconfig/infernalexp-server.toml `
