### ISSUE TITLE
I played beta8. I created a portal and then when i tried to go in the portal, it crashed. The game always crashes.

### ISSUE THREAD

**Issue by ddship12** [nekomaster1000/Infernal-Expansion#191]
**Describe the Bug:**
I created a portal so I can go to Nether. I tried to enter the portal but the game crashed. I tried 3 times. 

**How to Reproduce:**
Step 1 is to load beta8 mod only. Step 2 is to set to creative mode. Step 3 click play
Step 4 create a portal using obsidian blocks, flint and steel
Step 5 try to go in the portal

**Expected Behavior:**
The portal should not crash. I should be able to go to Nether to see the desolate Bastion. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/83261580/126865512-1cd27685-c120-4405-ab05-cde64666b471.jpeg)

**Version Information:**
 - Operating System: Windows 10
 - Mod Version: beta8
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.62
 - Other mods that were running when the crash happened: infernal expansion beta8 and abnormals core 1.16.5 -3.2.0 but i also tried this without abnormals core and same result. 

**Additional Context:**

**Comment by SwanX1** [comment]
Hello, if you could provide more information about your issue, by filling out the form in the issue, that'd be great.

**Comment by ddship12** [comment]
Hi Swan. I add the details and screenshot already.

**Comment by SwanX1** [comment]
Thank you! Unfortunately, this doesn't give me any information I need :(
Could you please get the **latest** crash report from your `.minecraft/crash-reports/` folder, upload it to [paste.gg](https://paste.gg/), and post it here?

**Comment by ddship12** [comment]
Here is the paste gg: https://paste.gg/p/anonymous/c37693fc02bf4199a24654525f5af827

**Comment by Dariensg** [comment]
The only way I was able to recreate this crash was by using the config blacklist to blacklist every single nether biome in the game. I've realized another way to cause this would be to turn on the whitelist and input an invalid biome, meaning that the whitelist is completely empty. Have you touched the blacklist/whitelist at all in the config?

**Comment by ddship12** [comment]
No I didn't touch blacklist or whitelist.

**Comment by Dariensg** [comment]
Could you upload a copy of your Infernal Expansion config file to [paste.gg](https://paste.gg/) as well and post it here? It should be in .minecraft/config/infernalexp-common.toml. Thanks!

**Comment by ddship12** [comment]
I don't see -common.toml. Inside infernalexp folder is spawnrates folder only. Look:
![image](https://user-images.githubusercontent.com/83261580/126873776-d9fd540f-fe1c-4435-9a42-61747eb1b17e.png)

**Comment by Dariensg** [comment]
It isn't in the infernalexp folder inside config. Back out one layer and it should be there, as listed in my comment above.

**Comment by ddship12** [comment]
Oh sorry. Here you go https://paste.gg/p/anonymous/7d523d30f06c4e21ba2bdecc8434dfa4

**Comment by Dariensg** [comment]
You've enabled the whitelist and put an invalid biome name into it. Change the value here: `biomesListIsWhitelist = true` to false and `biomesList = "infernalexp:delta_shores"` to an empty quote. The new lines should be `biomesListIsWhitelist = false` and `biomesList = ""`.
