### ISSUE TITLE
Glowsilk Bow arrows could fly twice as far as normal arrows

### ISSUE THREAD

**Issue by nekomaster1000** [nekomaster1000/Infernal-Expansion#194]
**Describe the addition:** What should we add or change to the mod to make it better?
Here's a thought: What if the Glowsilk Bow's arrows flew twice as far as that of a regular bow's? 
This would make it more useful in both hitting enemies from further away and lighting up places/enemies in the dark!

**Comment by Dariensg** [comment]
I could see doing this, but at the same time we don't want to make the bow _too_ powerful. I think, possibly, for the price of the Glowsilk that it takes to make the bow, this might be a reasonable balance.
