### ISSUE TITLE
AvoidBlockGoal Crash in Overworld [WIP]

### ISSUE THREAD

**Issue by Liamdude** [nekomaster1000/Infernal-Expansion#196]
**Describe the Bug:**
On starting a new world, I experienced a crash shortly after loading. I was moving toward a dungeon created by When Dungeons Arise, and the game suddenly crashed.

**How to Reproduce:**
From the crash log, it looks like Apotheosis might be involved. I will be testing to reproduce this later today, but I wanted to notify you about it sooner rather than later. I will update when I have more information about the source of this crash.

**Expected Behavior:**
That the game would not crash where I was. I was in the overworld and not the Nether, so I was surprised to see Infernal in the crash log.

**Version Information:**
 - Operating System: Windows
 - Mod Version: 2.0.0-beta.8
 - Minecraft Version: 1.16.5
 - Forge Version: 1.16.5-36.2.0
 - Other mods that were running when the crash happened: It's a large mod list that should be visible in the crash log. I will test with a condensed list.

**Additional Context:**
Crash log and mod list: https://pastebin.com/tggwL3Dt

**Comment by Dariensg** [comment]
Could you do me a huge favor by just removing Infernal Expansion, going to that dungeon, and seeing what mob spawner types are in there? I have a theory about what's causing the crash, but I need to know what modded mobs are trying to spawn and what mod they come from.

As a brief summary, this crash appears to be happening when something that is based on a Magma Cube spawns, but uses different movement type than a Magma Cube, therefore our code that makes Magma Cubes avoid the Glow Light blocks tries to be added to the new mob, but crashes the game since they use a different movement type. Thank you for your help!

**Comment by Liamdude** [comment]
It's definitely something related to magma slimes. The mobs I found were combinations between Skeletons and magma slimes. However, the actual spawner said it was just for skeletons. I can try reaching out to the dev in their Discord to figure out what exactly this combination mob is supposed to be.
![2021-07-26_11 38 01](https://user-images.githubusercontent.com/41766967/127018017-fc3db826-be5e-46a9-b708-e94e8bb4b9db.png)

![2021-07-26_11 37 32](https://user-images.githubusercontent.com/41766967/127017885-dd2b62bd-bc85-4ab9-9668-c63b7283ee4f.png)

**Comment by Dariensg** [comment]
That is really strange. The Mob UI thing says that it's a Pyro Skeleton, but it's from Minecraft, which obviously can't be right. Were these added by the Dungeon mod? I looked and the mod isn't open source, so there's not much I can do to look at their code and figure out what causes the issue. If you could reach out to them, that would be great! I'd love to get this resolved!

**Comment by Liamdude** [comment]
Devs are actually aware of this exact issue. A spawner in their small blimp structure creates regular skeletons (ignore the Pyro in the name) that have magma slimes mounted on their heads. The solution right now seems to be to disable the structure from spawning when played with Infernal. The devs are considering removing the spawner to make compatibility easier.

**Comment by Dariensg** [comment]
Sounds good! I'll close this issue since it seems to come from their end and they have a solution for it, would you mind telling me how you were able to contact them? I'd love to reach out and see if we could work out a fix without them having to remove the spawner!

**Comment by Liamdude** [comment]
They have a discord server here: https://discord.com/invite/wJfUere7sA

**Comment by Dariensg** [comment]
Thanks! Closing this issue now as it's not on IE's side!

**Comment by Dariensg** [comment]
Reopening as I discovered this actually is on our side and is an easy fix. We will commit a fix shortly!
