### ISSUE TITLE
Bonemeal interactivity for Nylium

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#200]
**Describe the addition:**
Just like with using bonemeal on moss, the same effect should be applied when bonemeal is used on crimson and warped nylium. Since nylium doesn't grow back, it would help to solve the annoying issue of converting a nylium block to netherrack when another block is placed on top.

**Comment by SwanX1** [comment]
This really isn't possible, since using bone meal on nylium already creates that nylium's-based foliage, like nether roots, or warped fungi.
