### ISSUE TITLE
Crash with Slime

### ISSUE THREAD

**Issue by SHXRKIEgg** [nekomaster1000/Infernal-Expansion#201]
**Describe the Bug:**
In the Nether is randomly Crashed

**How to Reproduce:**
Create a Portal to the Nether 
Enter the Nether
Crashes

**Expected Behaviour:**
Not to Crash

**Version Information:**
 - Operating System: Windows 10
 - Mod Version: infernal-expansion-2.0.0-beta.8.jar
 - Minecraft Version: 1.16.5
 - Forge Version: 31.2.2
 - Other mods that were running when the crash happened: [Better Minecraft Modpack](https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack)

**Additional Context:**
Crash - https://pastebin.com/zxcCypbs

**Comment by Dariensg** [comment]
This is a duplicate of Issue #196. This crash is fixed in the latest release (2.0.0), while you are still using the older beta. Update to the newest version for this fix!
