### ISSUE TITLE
Biomes O' Plenty Compat

### ISSUE THREAD

**Issue by tikiMC** [nekomaster1000/Infernal-Expansion#203]
When Biomes O' Plenty is installed the glowstone canyon doesn't generate.

Load the game with Infernal Expansion and Biomes O' Plenty installed, travel to the nether and look around or use /locatebiome.

For the glowstone canyon to generate regardless of what other biome mods are present

 - Mod Version: 2.0.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.25
 - Biomes O' Plenty: 13.1.0.477

**Comment by SwanX1** [comment]
Go into your installation wherever it is. Find the config folder and go into that.
Go into the `biomesoplenty` folder. Go into the `generation.toml` file. Find the line that is called `"use_bop_nether"` and change the value to `false`.
Save, exit, potentially reload the game. Start a new world using the Biomes O' Plenty World Type.
