### ISSUE TITLE
Glowsilk bow and tipped arrows issues

### ISSUE THREAD

**Issue by tikiMC** [nekomaster1000/Infernal-Expansion#204]
- Regular Arrows shot out of the glowsilk bow turn into uncraftable tipped arrows with the luminance effect when picked up. Also already tipped arrows when shot out of the glowsilk bow turn into arrows with 2 potion effects.
 
- Arrows of luminance give the effect for 3 minutes instead of 22 seconds, 1 minute(extended). This is also the case when shot out of the glowsilk bow regardless of what arrow was used. Lastly the arrow of luminance 2 gives you luminance 2 for 11, but then gives luminance 1 for the remaining 2:49 seconds adding up to the unintended 3 minutes once again.

 - Mod Version: 2.0.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.25

**Comment by Dariensg** [comment]
I'll have to look into most of these, but the 2 potion effects produced from tipped arrows is actually intentional! The bow is meant to fire arrows with potion effects and also add the Luminance effect to them. I will have to get back to you on the rest of those issues!

**Comment by tikiMC** [comment]
Okay just making sure I sort of thought it was intentional! I like how the color changes on the arrow :D
