### ISSUE TITLE
Shroomlight Tear - Bone meal

### ISSUE THREAD

**Issue by tikiMC** [nekomaster1000/Infernal-Expansion#205]
Shroomlight Tears only grow on the bottom of the shroomlight. You can't even use bone meal on a shroomlight block if there isn't a air space under it.

I expect this is unintended because you can find them growing atop the block in the world.

**Comment by nekomaster1000** [comment]
They only grow atop Shroomlight found in the _Warped Forest,_ it's an unnatural growth spurred on by the biome that can also be seen in the Twisted Vines. this is intended behaviour.
