### ISSUE TITLE
Compatibility With Autumnity's Giant Jack-O-Lanterns

### ISSUE THREAD

**Issue by TheLemonLimeBrony** [nekomaster1000/Infernal-Expansion#216]
Autumnity has those giant Jack-O-Lanterns that you can make, and Endergetic Expansion adds compatiblity with it for their enderlight torches. Infernal Expansion should add compatibility for the glowlight torches

**Comment by SwanX1** [comment]
PR for this issue has been created: team-abnormals/autumnity#98, waiting on them to merge it.

**Comment by Dariensg** [comment]
Just wanted to update you on the situation. Team Abnormal's license forbids us from doing compat on our side as it would require using some of their code and we tried to contact them for explicit permission with no luck. We gave a PR for compat, containing all the code and files they would need for this, and they have not merged it. Thus, unless they change their mind, compat with Autumnity is not possible at the moment. We will update you if anything changes.

**Comment by Dariensg** [comment]
Another update: We've spoken with Team Abnormals and they've made it clear that they have no intention of implementing our PR at any point. As such, there is nothing we can do on our side to add this compatibility short of adding a dependency or making a secondary addon mod specifically for Autumnity. We apologize for this inconvenience, but it is out of our hands. I will be closing this issue now.
