### ISSUE TITLE
In-Game Config Doesn't Save Written Entries to File in IE 2.0

### ISSUE THREAD

**Issue by nekomaster1000** [nekomaster1000/Infernal-Expansion#220]
When writing biome IDs into the Mob Spawning config boxes, it should save them to file upon pressing done. It doesn't.
![In-Game Config Doesn't Save Written Entries to File](https://user-images.githubusercontent.com/47757977/127724238-896c6422-c136-4985-bfa6-426f366bb9c8.png)

**Comment by caelwarner** [comment]
smh @nekomaster1000 , literally the owner of the whole project and you couldn't even bother to use the issue template

**Comment by Dariensg** [comment]
Could not replicate, closing this issue.
