### ISSUE TITLE
Infernal Painting Crash

### ISSUE THREAD

**Issue by RhysNorton** [nekomaster1000/Infernal-Expansion#228]
**Describe the Bug:**
I placed an infernal painting for the first time and my game crashed and continues to crash anytime I open the world

**How to Reproduce:**
1. Craft an infernal painting in survival
2. Place a painting
3. Game crashes
3. Reload world after crash
4. Game crashes again

**Expected Behavior:**
I expect the infernal painting to be placed like any vanilla painting

**Screenshots:**

**Version Information:**
 - Operating System: Windows
 - Mod Version: 2.0.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.65
 - Other mods that were running when the crash happened:

- Abnormals Core
- Abnormals Delight
- Allurement
- Appleskin
- Attribute Fix
- AutoRegLib
- BedBenefits
- Berry Good
- Better Burning
- Better Drowning
- Better Strongholds
- Better Trident Return
- Big Brain
- Bookshelf
- Buzzier Bees
- Catalogue
- Configured
- Desolation
- Disenchant
- Endergetic Expansion
- Enhanced Mushrooms
- Environmental
- Farmers Delight
- Farmers Delight Integration
- Farmers Tea
- Fast Furnace
- Fast Leaf Decay
- Fast Workbench
- Gamemode Overhaul
- Infernal Expansion
- Just Enough Items
- Just Enough Resources
- Outposter
- Placebo
- Quark
- Random Patches
- Serene Seasons
- Shutup Experimental Settings
- Simply Tea
- Sodium
- Spice of Life - Carrot Edition
- Straw Golem
- Swing Through Grass
- Trample Stopper
- Upgrade Aquatic
- What The Hell Is That
- Yungs API

**Additional Context:**
I had installed an updated version of the mod before entering the nether in this world, but this was the only problem I experienced.

**Comment by SwanX1** [comment]
Please provide a crash report.

**Comment by evanbones** [comment]
Sodium issue, update sodium

**Comment by RhysNorton** [comment]
Thank you for your response, evanbones. I updated sodium and that fixed the issue :)
