### ISSUE TITLE
mobs of the mod dont make noise in multiplayer servers

### ISSUE THREAD

**Issue by ThsHaunted124** [nekomaster1000/Infernal-Expansion#24]
So far ive noticed that embodies and volines dont make any noise in multiplayer servers. I dont know about other mobs of the mod but there is a very good chance they also dont make noise.

**Comment by SwanX1** [comment]
I cannot recreate the issue on neither release 1.3, nor the latest dev build. Can you tell me your minecraft, forge, and mod versions?
If you could send a client log too, that would be great.

**Comment by ThsHaunted124** [comment]
Hello. 
The minecraft version is 1.16.5 and  the forge version is 36.0.42. Im not sure where i can find the client log but this is what if could find ( https://pastebin.com/tPiHb9V0 ). 

Im using multimc to run a little modpack i threw together.
along this mod i am using: 
-betterendforge-1.16.4-1.5.0
-DynamicSurroundings-1.16.4-4.0.3.8
-endergetic-1.16.4-3.0.0
-Quark-r2.4-303
-OptiFine_1.16.5_HD_U_G6
-alexsmobs-1.5.1
-upgrade_aquatic-1.16.5-3.0.1
-BiomesOPlenty-1.16.4-13.0.0.431-universal
-geckolib-forge-1.16.5-3.0.13
-repurposed_structures-1.16.4-2.3.4
-CraftTweaker-1.16.5-7.1.0.126
-Druidcraft-1.16.5-0.4.52
-EnigmaticLegacy-2.10.3
-savageandravage-1.16.4-3.0.0
-abnormals_core-1.16.4-3.0.6
-infernal-expansion-forge-1.3
-Patchouli-1.16.4-50
-decorative_blocks-1.16.4-1.7.2
-extcaves-2.4
-citadel-1.6.1
-the-conjurer-1.16.4-1.0.13
-dungeons_plus-1.16.4-1.1.3
-carryon-1.16.3-1.15.1.7
-Bookshelf-1.16.5-10.0.1
-BetterMineshafts-Forge-1.16.4-2.0.1
-structure_gel-1.16.4-1.7.5
-curios-forge-1.16.5-4.0.4.0
-champions-forge-1.16.5-2.0.1.3
-Waystones_1.16.3-7.3.1
-travellers_map-1.16.3-0.7.5
-spiders-2.0-1.16.4-1.0.4
-Placebo-1.16.4-4.4.1
-tumbleweed-1.16-0.4.9
-walljump-forge-1.16.4-1.3.7
-backpacked-1.7.0-1.16.3
-mining-helmet-1.16.4-2.0.0
-YungsApi-1.16.4-Forge-4
-AutoRegLib-1.6-47
-scuba-gear-1.16.5-1.0.2
-AppleSkin-mc1.16.2-forge-1.0.14
-swingthroughgrass-1.16.4-1.5.3
-ChunkAnimator-1.16.5-1.2.0
-FastLeafDecay-v25
-overloadedarmorbar-5.1.0
-toughnessbar-6.1
-toughnessbar-6.1
-leap-1.16.4-1.0.1
-HerdMentality-1.16.5-6.0.1
-QuarkOddities-1.16.3

Is there anything else i can do to help out?

**Comment by SwanX1** [comment]
Hi! Unfortunately, I couldn't reproduce this bug. If you can reproduce it, please reopen this issue **with a narrowed down modlist.**
