### ISSUE TITLE
The game crashes when i press "create a new world" button and removing infernal expansion fixes it

### ISSUE THREAD

**Issue by Atopik2** [nekomaster1000/Infernal-Expansion#240]
**Describe the Bug:**
The game crashes when i press "create a new world" button and removing infernal expansion fixes it

**How to Reproduce:**
I dont know but i have the crash report

**Expected Behavior:**
The game to create a world

**Version Information:**
 - Operating System:Windows 10 pro
 - Mod Version:2.1.1
 - Minecraft Version:1.16.5 forge
 - Forge Version:latest 1.16.5
<details>
  <summary>Other mods that were running when the crash happened</summary>

  - YUNG's Better Dungeons
  - Goki Stats
  - Big Brain
  - Infernal Expansion
  - That future mod
  - Nether's Exoticism
  - ToroHealth
  - Stalwart Dungeons
  - Looot
  - Farmer's Delight Compats
  - YUNG's API
  - Pyromancer
  - Guard Villagers
  - Snow! Real Magic!
  - Just Enough Resources
  - BetterEnd Forge
  - Upgraded Netherite
  - Structure Gel API
  - Advancement Plaques
  - Castle in the sky
  - Clean Cut
  - Repurposed Structures
  - More Villagers
  - Biomes O' Plenty
  - Dungeons Plus
  - Simply Improved Terrain
  - Extended Caves
  - Better Default Biomes
  - Darker Depths
  - spark
  - Mo' Structures
  - Curios API
  - Origins
  - Better Weather
  - Mushroom Quest
  - Obfuscate
  - TheAbyss
  - Majrusz's Progressive Difficul
  - Astemir Forest Craft
  - Cloth Config v4 API
  - bgcore
  - Tom's Simple Storage Mod
  - Custom Starter Gear
  - Exotic Birds
  - YUNG's Better Mineshafts
  - Stables
  - Dungeons Gear
  - Kiwi
  - Mowzie's Mobs
  - Just Enough Items
  - Comfortable Nether
  - AttributeFix
  - Pehkui
  - Jellyfishing
  - Goblin Traders
  - Caelus API
  - Organics
  - Nature's Compass
  - StructuresAdventures
  - Untamed Wilds
  - WorldbuildingGen
  - Stoneholm
  - Upstream
  - Champions
  - Outvoted
  - Forge
  - Off Hand Combat
  - Subterranean Wilderness
  - SpawnBalanceUtility
  - §3Dynamic Surroundings
  - When Dungeons Arise
  - permafrost_biome
  - Minecraft
  - CoFH Core
  - Pandoras Creatures
  - Mouse Tweaks
  - Spheric
  - Greek Fantasy
  - Majrusz Library
  - Evolved RPG
  - Whisperwoods
  - Flywheel
  - Mantle
  - Gravestone Mod
  - Polymorph
  - AutoRegLib
  - Regrowth Mod
  - Global Data- & Resourcepacks
  - Wesley's Roguelike Dungeons
  - Nef Deco Mod
  - Oh The Biomes You'll Go
  - Aquaculture 2
  - Orcinus's Cavern
  - Betterlands
  - The Farlanders
  - Structure plus ii
  - HT's TreeChop
  - Dungeons Mod
  - Blue Skies
  - UnionLib
  - Wyrmroost
  - Eidolon
  - Doggy Talents 2
  - The Afterlight
  - InsaneLib
  - Xaero's World Map
  - EnhancedVisuals
  - Controlling
  - Citadel
  - Alex's Mobs
  - Ice and Fire
  - Rats
  - Mutant Beasts
  - Sophisticated Backpacks
  - Relics
  - Progressive Bosses
  - FPS Reducer
  - Dragon Mounts: Legacy
  - Lost Trinkets
  - The Twilight Forest
  - Konkrete
  - Cuneiform
  - Ore Tweaker
  - Chocolate
  - Undead Expansion
  - Farmer's Delight
  - Farmers Delight Cookbook
  - Project: Vibrant Journeys
  - End Remastered 3.6
  - Lollipop
  - Dungeons Enhanced
  - Village Spawn Point
  - Creatures and Beasts
  - GeckoLib
  - Patchouli
  - Feywild
  - Ars Nouveau
  - Collective
  - Xaero's Minimap
  - Survive
  - Desolation (Forge)
  - Enigmatic Legacy
  - Builders Crafts & Addition
  - Architectury
  - The Undergarden
  - Enchant With Mob
  - InstantUnify
  - Shrines
  - Druidcraft
  - The Conjurer
  - Dungeons Mobs
  - Abnormals Core
  - Upgrade Aquatic
  - The Endergetic Expansion
  - Savage & Ravage
  - Autumnity
  - UNDEAD
  - Toad Terror
  - Ensorcellation
  - Create
  - YUNG's Better Portals
  - Village Employment
  - Bloxys Structures
  - Artifacts
  - The Outer End
  - Dungeon Crawl
  - BadMobs
  - LazyDFU
  - Mahou Tsukai
  - Farsight mod
  - Wandering Bag
  - Akashic Tome
  - Traveler's Titles
  - Tinkers' Construct
  - Jade
  - CreativeCore
  - Archer's Paradox
  - Towers Of The Wild
  - Atmospheric
  - Quark
  - Charm
  - Terra Incognita
  - Diet
  - Adaptive Performance Tweaks
  - Performant
  - FancyMenu
  - Tiered
  - Workshops of Doom
  - Hunter Illager
  - Danny's Expansion
  - Ferrite Core
  - Odd Water Mobs
  - Enhanced Celestials
  - Illagers+
  - ExpandAbility
  - Valhelsia Core
  - Valhelsia Structures
  - Overloaded Armor Bar
</details>

**Comment by SwanX1** [comment]
Please provide a crash report.

**Comment by Atopik2** [comment]
> Please provide a crash report.

[crash-2021-08-08_00.43.51-client.txt](https://github.com/infernalexp/Infernal-Expansion/files/6951041/crash-2021-08-08_00.43.51-client.txt)

**Comment by SwanX1** [comment]
this crash report doesn't even have infernal expansion listed as one of the mods and doesn't relate to infernal expansion at all
