### ISSUE TITLE
Craftable Glowsilk bow removal

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#246]
**Describe the addition:**
The old Glowsilk bow recipe still exists, making the bow easier to get by crafting instead of using the smithing table. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/49106149/128705856-d50cba31-8918-4267-ba84-8312f866b53d.png)

**Comment by Dariensg** [comment]
That recipe is intended and is no easier than the smithing recipe.
