### ISSUE TITLE
Crash when attacking glowsquito.

### ISSUE THREAD

**Issue by Wedge1453** [nekomaster1000/Infernal-Expansion#248]
I was in a glowstone canyon attacking a bung of glowsquitos with a trident, and suddenly the game crashed, here's the log:
[crash-2021-08-08_19.59.06-client.txt](https://github.com/infernalexp/Infernal-Expansion/files/6955475/crash-2021-08-08_19.59.06-client.txt)
not sure if the issue in on infernal's end.

**Comment by SwanX1** [comment]
Can you please send your log too (not the crash report)?
Is this issue reproducible (repeatable)? If so, please list the steps to do so.

**Comment by SwanX1** [comment]
Closing due to no response.

**Comment by Wedge1453** [comment]
sorry I wasn't succesful in replicating it, I'll let you know if I figure it out.
