### ISSUE TITLE
Glowstone Canyon is not tagged in the biome dictionary

### ISSUE THREAD

**Issue by Vazkii** [nekomaster1000/Infernal-Expansion#262]
The biome isn't tagged in forge's biome dictionary, this causes quark's features to spawn in it erroneously.

![GbV1tj7a](https://user-images.githubusercontent.com/1794735/129362912-7f61687f-fa5a-44fd-b6f5-dea7b970d220.jpg)

**Comment by caelwarner** [comment]
Thanks for your help!
