### ISSUE TITLE
[BUG 1.16.5] NO STARTING SERVER

### ISSUE THREAD

**Issue by MrJorman** [nekomaster1000/Infernal-Expansion#264]
please update mixin for your mod, as I can't start the server with your mod on the new Forge.

i use core: Lolliserver 1.16.5
log: https://paste.ubuntu.com/p/X4jCnqjGbd/

**Comment by SwanX1** [comment]
Hi! Unfortunately we don't support any other environments than Minecraft Forge, you're using unsupported server software.

See: [Issue #158 Comment](https://github.com/infernalexp/Infernal-Expansion/issues/158#issuecomment-880640563)
