### ISSUE TITLE
This mod doesn't work with biome datapack

### ISSUE THREAD

**Issue by Jukabofy** [nekomaster1000/Infernal-Expansion#265]
**Describe the Bug:**
The new biome of this doesn't appear with a biome datapack called: Netherlands v1.1: 10 new Nether biomes! (1.16.5 Experimental World Gen) https://www.planetminecraft.com/data-pack/netherlands-v1-0-10-new-nether-biomes-1-16-2-experimental-world-gen/
I tried to use the command /locatebiome but it just say something like it cannot be found at a considerable distance

**How to Reproduce:**
Start a map with that datapack and twist mod maybe

**Expected Behavior:**
I think is the datapack, I don't have another mod that change generation just it and Twist mod

**Screenshots:**
![noname](https://user-images.githubusercontent.com/87483832/129809972-06de84bb-526e-48ad-b9f6-22c3997b87ac.png)
![noname](https://user-images.githubusercontent.com/87483832/129810138-638277d9-1b27-451a-a497-50cc7ce85531.png)
Just one of the four structures of this mod can be found
![noname](https://user-images.githubusercontent.com/87483832/129810208-462e0692-cf09-41ba-b538-21baa83fcd38.png)

**Version Information:**
 - Operating System: Windows 10
 - Mod Version: the last one
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.0
 - Other mods that were running when the crash happened:
 - 
![noname](https://user-images.githubusercontent.com/87483832/129810505-984bfd7a-ccae-43bc-8b90-5680301d5a41.png)

**Additional Context:**
Is just the biome and some of the structures, the mobs spawn properly in the biomes

**Comment by XionioXMaster** [comment]
Incedium data-pack also cannot support biomes from the mod

**Comment by Jukabofy** [comment]
Anyway Is not totally vanilla friendly that datapack.
Is an inconvinience to try compatibility between different kind of files,
