### ISSUE TITLE
World save lag

### ISSUE THREAD

**Issue by someaddons** [nekomaster1000/Infernal-Expansion#270]
**Describe the Bug:**
Infernal expansions causes excessive lag on world saves every 5 minutes. 

https://spark.lucko.me/1WSS7oba1E

**How to Reproduce:**
Load the world with the newest infernal expansion, wait a bit then press escape(triggers a save) watch how the save takes serveral seconds.

**Expected Behavior:**
Not to lag

**Screenshots:**

**Version Information:**
 - Operating System:
 - Mod Version: 2.2.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.2
 - Other mods that were running when the crash happened:

Using this pack: https://www.curseforge.com/minecraft/modpacks/adventures-and-dungeons-a-d/files/3436867

**Additional Context:**

**Comment by Neko2n** [comment]
I was waiting to see if anyone would post this issue before I did. Been having the same issue on a private pack.

**Comment by SwanX1** [comment]
<details>
<summary>Mentioned Users</summary>

 - @someaddons
 - @NovaN4 
</details>

Please let me know if using this version of the mod doesn't fix your issue: [infernalstudios.org/etc/infernal-expansion-2.2.0+20210829.1.jar](https://infernalstudios.org/etc/infernal-expansion-2.2.0+20210829.1.jar)

**Comment by Neko2n** [comment]
That version fixes the issue for me, no more freezes even with 300 other mods. Thanks!

**Comment by HadesDeadlyTom** [comment]
Yes ! i had a error spam on my server : "Base value out of range: 256 [-10-128]" that overloaded the RAM and crashed the server.
This fixed it, thanks !
