### ISSUE TITLE
Fire isn't blue on Soul Stone

### ISSUE THREAD

**Issue by TheRealZonko** [nekomaster1000/Infernal-Expansion#271]
Soul Soil and Soul Sand have blue fire when ignited, but not Soul Stone

**Comment by SwanX1** [comment]
![image](https://user-images.githubusercontent.com/36593309/131319352-9518f74e-cb00-411e-9c29-8b481e12e637.png)
idk what you're on buddy, but it works
soul stone is also in the [appropriate tag](https://github.com/infernalexp/Infernal-Expansion/blob/2b3fb682b9dc96f18492e7740a845fc99f34708e/src/main/resources/data/minecraft/tags/blocks/soul_fire_base_blocks.json#L8)
