### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by CombinL0N** [nekomaster1000/Infernal-Expansion#273]
**Describe the Bug:**
5 crashes when starting up.

**How to Reproduce:**
Just startup the game.

**Expected Behavior:**
I had no expectation.

![image](https://user-images.githubusercontent.com/28372310/131266411-6178bffa-9417-4a32-ba56-cd05acb55cd3.png)

**Version Information:**
 - Operating System: Windows 10
 - Mod Version: 2.2.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.2
 - Other mods that were running when the crash happened: (Exclude the folders)
![image](https://user-images.githubusercontent.com/28372310/131266387-8ffebe93-0b85-4a7a-9b8f-0022761d5d04.png)

**Additional Context:**
N/A

**Comment by SwanX1** [comment]
Please post a crash report

**Comment by thelegitdolt** [comment]
i believe i am running into this issue as well. same crash notice, everything.  it's likely caves and cliff backport; that mod's known to be pretty unstable. I'll post the logs right here.

https://cdn.discordapp.com/attachments/673992406697377792/889362850945060895/crash-2021-09-19_21.06.47-fml.txt

**Comment by caelwarner** [comment]
@thelegitdolt If you have the time, could you do me a huge favour and trying running the game again with caves and cliffs backport removed? Thanks!

**Comment by thelegitdolt** [comment]
@caelwarner yea sure, I'll do that after I get home from school.

**Comment by thelegitdolt** [comment]
i was wrong, it would appear that it's not the mod lol. 
it's definitely one of the mods that me and denver here both have, though.
![](https://media.discordapp.net/attachments/793364167364313090/888917494570582066/Screen_Shot_2021-09-18_at_3.40.29_PM.png)
![](https://media.discordapp.net/attachments/793364167364313090/888917501717671976/Screen_Shot_2021-09-18_at_3.40.12_PM.png?width=1296&height=1323)

**Comment by SwanX1** [comment]
This is most likely an issue with More Waterlogging. (I think this has happened before?)

**Comment by Dariensg** [comment]
Updating More Waterlogging to 1.5, the latest version, should fix the issue!

**Comment by thelegitdolt** [comment]
awesome, much thanks
