### ISSUE TITLE
glowstone biome appearing in overworld

### ISSUE THREAD

**Issue by MayD524** [nekomaster1000/Infernal-Expansion#276]
**Describe the Bug:**
Glowstone biome generating in overworld

**How to Reproduce:**
I had added 1 mod to the pack I am playing on

**Expected Behavior:**
I expected nether biomes to remain in the nether

**Screenshots:**

**Version Information:**
 - Operating System: Windows 10
 - Mod Version: 2.2.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.2
 - Other mods that were running when the crash happened:

**Additional Context:**

**Comment by SwanX1** [comment]
pleasrle list any other mods you have installed

**Comment by MayD524** [comment]
Sorry for the late reply. This pack is currently being run on a server, and all the mods played well together until we attempted to update and adding Refined storage, I'm unsure if there is a bug there but removing it and replacing it with AE2 seemed to work.
Full mod list:
BetterEnd
Guard Villagers
Selene
Supermentaries
Tiny Redstone
Abnormals Core
Alex's Mobs
AppleSkin
Applied Energistics 2
AstikorCarts
Biomes 0' Plenty
Carry On
Chisels & Bits
Citadel
Comfortable Nether
Create
Croptopia
Damage Tilt
Dynamic Trees & Dynamic Trees BoP
Easier Sleeping
Extra Boats
Farmers Delight
Flywheel
Immersive engineering
Infernal Expansion
Iron Chests
JourneyMap
JEI
JournyMap
Macaw's  Roofs
Minecoprocessors
Mouse Tweaks
MrCrayfish's Furniture Mod
Neat
Pams HarvestCraft 2
Paragliders
silent lib
spartan shields
spartan weaponry
swing through grass
travelers backpacks
upgrade aquatic
upgraded netherite
valhelsia core
valhelsia structures
waddles

**Comment by caelwarner** [comment]
What modpack is this? Also was the glowstone canyon generating in the overworld before you added the one extra mod. And, finally just to confirm, was the mod you added Refined Storage?
