### ISSUE TITLE
Glowsilk Bow pulling animation goes to default bow.

### ISSUE THREAD

**Issue by itsdeelee** [nekomaster1000/Infernal-Expansion#279]
**Describe the Bug:**
When firing an arrow using the Glowsilk Bow, the pulling animation shows the default minecraft bow.
This happens when I'm in creative or survival mode, with or without enchantments.

**How to Reproduce:**
Grab a Glowsilk Bow and fire an arrow.

**Screenshots:**
https://imgur.com/KAWgRtB

**Version Information:**
 - Operating System: Windows 10
 - Mod Version: 2.2.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.2
 - Other mods that were running when the crash happened:

**Additional Context:**
The modpack I'm using is **Crucial 2 - The Refresh Update** (on curseforge) so I can list all the mods it uses if needed.

**Comment by caelwarner** [comment]
I've tried replicating this bug across multiple different environments including in Crucial 2 and I can't. Leaving this open for a few more days in case of new information.

**Comment by itsdeelee** [comment]
> 
> 
> I've tried replicating this bug across multiple different environments including in Crucial 2 and I can't. Leaving this open for a few more days in case of new information.

After further testing, I seemed to have found the issue when using a Vanilla Tweaks resource pack that fixes item stitching.
The solution was to just remove the bow.json / bow_pulling_0.json / bow_pulling_1.json / bow_pulling_2.json files from the resource pack models/item folder.

The item stitching on the bow doesn't affect me that much, but I linked the files below using pastebin (**warning the bow_pulling files are long**).
[bow.jason](https://pastebin.com/s83mS1Qc)
[bow_pulling_0.json](https://pastebin.com/PRQCd22J)
[bow_pulling_1.json](https://pastebin.com/fni4rwkM)
[bow_pulling_2.json](https://pastebin.com/5jXLHtPX)

**Comment by SwanX1** [comment]
I don't think that this issue is something we can fix, sorry.
