### ISSUE TITLE
Crash when entering Nether

### ISSUE THREAD

**Issue by madartist0** [nekomaster1000/Infernal-Expansion#280]
**The Bug:**
game crashes when loading the nether (Exit Code: 0)

**How to reproduce:**
Every time I create a world and enter the nether the game crashes. Tested with only Infernal Expansion in mods folder and game still crashes.

**Expected Behavior:**
The game to not crash.

**Version Information:**
 - Operating System: 2019 MacOS Catalina 10.15.6
 - Mod Version: tested using release 2.0.0 to 2.2.0
 - Minecraft Version: 1.16.5
 - Forge Version: 1.16.5 - 36.2.0
 - Other mods that were running when the crash happened: None

**Additional Context:**
I've never had this happen before, I've used this mod before and I really enjoy it, I don't know what happened to cause this now.

**Comment by SwanX1** [comment]
crash report?
if you can't view a log, launch using multimc or gdlauncher, they can provide logs

**Comment by madartist0** [comment]
launched with multimc the game has no issue running the mod. using the vanilla launcher's game output I got the message "Processes crashed with exit code 255", using vanilla launcher while also having [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) and [NotEnoughCrashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge) installed leads to the "crash" saying "disconnected from server" and then sending me to the multiplayer menu.

**Comment by madartist0** [comment]
> crash report?
> if you can't view a log, launch using multimc or gdlauncher, they can provide logs

launched with multimc the game has no issue running the mod. using the vanilla launcher's game output I got the message "Processes crashed with exit code 255", using vanilla launcher while also having [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) and [NotEnoughCrashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge) installed leads to the "crash" saying "disconnected from server" and then sending me to the multiplayer menu (which is, I think, NEC's intended behavior when the game is going to crash).

**Comment by SwanX1** [comment]
Yeah, we kinda need the full log if we were to help you. Right now you're not giving us much to work with...
Please use a paste service like [paste.gg](https://paste.gg)

**Comment by madartist0** [comment]
> Yeah, we kinda need the full log if we were to help you. Right now you're not giving us much to work with...
> Please use a paste service like [paste.gg](https://paste.gg)

the game itself isnt providing much information. like I said I don't get a crash using multimc, therefor no crash report. this does technically solve my problem though. I just don't know why the vanilla launcher is having issues. I think this issue is on my end, not yours, sorry.

**Comment by caelwarner** [comment]
We are asking for a log, not a crash report. Logs get generated every time you launch the game. The logs are then stored in `/logs` in your Minecraft directory. Run the game, then reproduce the crash then send us `logs/latest.log`. Thanks
