### ISSUE TITLE
Code suggestion:use my biome api

### ISSUE THREAD

**Issue by Trinsdar** [nekomaster1000/Infernal-Expansion#284]
**Describe the addition:**
Instead of replacing the biome provider, you should simply use this: 
https://github.com/Reforged-Mods/FabricBiomeApiReforged

**Additional Context:**
Only qualm is that means you require another dep,  but imo that isn't really a big deal, it's better than compat issues.

**Comment by SwanX1** [comment]
no.

**Comment by Trinsdar** [comment]
Just curious: why?

**Comment by Dariensg** [comment]
For one, we avoid any and all dependencies, whether soft or hard dependencies. In extension to that, our current system works perfectly fine and has no compat issues that we are aware of at the moment. Our code pulls in other mods' nether biomes and incorporates them into our biome provider. If there's a biome you don't want, we have a blacklist/whitelist option built-in for our biome provider. We can perfectly have a world working with TerraForged, Biome O'Plenty, Oh the Biomes You'll Go, and more with 0 compat issues. If you find compat issues, please report them! We'd be happy to take a look. But, as is, there are no issues with how we handle our biome provider. It's very similar to how other mods with Nether Biomes handle their biomes.

**Comment by Trinsdar** [comment]
Ah ok, makes sense
