### ISSUE TITLE
Upgrading a Bow to the Glowsilk Bow requires a Glowsilk Cocoon, which is unobtainable.

### ISSUE THREAD

**Issue by Flexo013** [nekomaster1000/Infernal-Expansion#287]
**Describe the Bug:**
Glowsilk bows are unobtainable (when upgrading existing bows), as JEI states you need a Glowsilk Cocoon to upgrade a bow:

![image](https://user-images.githubusercontent.com/4507015/133931351-b7908d4a-4dd4-4227-a0a1-25b1481674a5.png)

**How to Reproduce:**
Try to upgrade a bow to a glowsilk bow.

**Expected Behavior:**
The recipe should use Glowsilk instead of Glowsilk Cocoon.

**Screenshots:**
The intended recipe doesn't work.

**Version Information:**
 - Operating System: Win10
 - Mod Version: 2.2.0
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.2
 - Other mods that were running when the crash happened: No crash, playing Crucial 2: Refresh, v1.3.3

**Additional Context:**
I talked to wasting my Bonnie on the Discord server, and they confirmed that this is a bug.

**Comment by caelwarner** [comment]
The recipe is correct, but Glowsilk Cocoons were unobtainable. They can now be obtained with a silk touch hoe.
