### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: org/infernalstudios/infernalexp/init/IEParticleTypes

### ISSUE THREAD

**Issue by Igorcmb** [nekomaster1000/Infernal-Expansion#290]
I was playing without any problems, but them it crashed and showed that error. I removed the mod and it seems to work, but if i put the mod again and try to load my world it crashes again with the same error. I have the glowstone glass on my base and that seems to be causing the error.

**Comment by Igorcmb** [comment]
[crash-2021-09-23_21.18.36-client.txt](https://github.com/infernalexp/Infernal-Expansion/files/7221414/crash-2021-09-23_21.18.36-client.txt)

**Comment by SwanX1** [comment]
Much More Mod Compat works as of commit b0a5f25e7b07e05a38aa31e69e64939312c5a43d (Release 2.1.0)
