### ISSUE TITLE
se cierra el juego al actualizar su mod

### ISSUE THREAD

**Issue by d-rick** [nekomaster1000/Infernal-Expansion#291]
**Describe the Bug:**
se cierra el juego al actualizar su mod y aparece el texto "error al cargar recursos"

[crash-2021-09-24_15.43.20-client.txt](https://github.com/infernalexp/Infernal-Expansion/files/7228339/crash-2021-09-24_15.43.20-client.txt)

MOD VERSION: Infernal Expansion Release 2.3.0

**Comment by SwanX1** [comment]
Please use English when writing an issue report.
