### ISSUE TITLE
1.16.5 Magma server crashes on start up.

### ISSUE THREAD

**Issue by seanimusprime** [nekomaster1000/Infernal-Expansion#292]
**Describe the Bug:**
When running a Magma (Forge server that can also run Spigot/Paper plugins) the server crashes during start up, getting hung up on a failed injection check. 

**How to Reproduce:**
Install magma server and start it up with Infernal Expansion.

**Expected Behavior:**
Server starts up.

**Screenshots:**

**Version Information:**
 - Operating System: Not sure what the server host is running, probably Linux of some type.
 - Mod Version: 2.3.1
 - Minecraft Version: 1.16.5
 - Forge Version: forge-1.16.5-36.2.4/Magma build ve8445f4
 - Other mods that were running when the crash happened:

**Additional Context:**
A cursory glance seems to point to something in this mod. The same issue happened in 2.3.0 as well and updating to 2.3.1 does not fix the issue.
This did not happen when we were running a "vanilla" Forge server. This only started happening when switching over to Magma.
Here is the last big error before the server crashes.
`[28Sep2021 00:28:12.911] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method IE_setCustomFireFromLava(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in infernal-expansion.mixins.json:common.MixinEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap infernal-expansion.refmap.json`

[debug.log](https://github.com/infernalexp/Infernal-Expansion/files/7241067/debug.log)
[latest.log](https://github.com/infernalexp/Infernal-Expansion/files/7241068/latest.log)

**Comment by SwanX1** [comment]
We don't support any software other than forge.
See issue #158

**Comment by seanimusprime** [comment]
> We don't support any software other than forge.
> See issue #158

Understandable. I know you marked it as closed, but here is the link to an open report to Magma. Might be useful to link to if this comes up again. https://github.com/magmafoundation/Magma-1.16.x/issues/151
