### ISSUE TITLE
Glow Biome needs a nether biome tag

### ISSUE THREAD

**Issue by GauntAndreX8** [nekomaster1000/Infernal-Expansion#293]
With the Danny expansion mod is spawned some over world desert related like the mummy and black scorpion, with Alex’s mobs when spawning like the gust or tarantula hawk they stay as overworld looks when I spawned instead of the nether relates and another bug not similar with this topic but the mushrooms get angry and attack on creative and spectator mode 

**Version Information:**
 - Operating System:
 - Mod Version: 2.3.1
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.0
 - Other mods that were running when the crash happened:

**Additional Context:**

**Comment by Dariensg** [comment]
The Glowstone Canyon already uses the Nether Biome Category. This most likely isn't an issue on our side.
