### ISSUE TITLE
When i add the newest update to my pack (2.3.2) my client tick increases by 10 ms

### ISSUE THREAD

**Issue by Mr-Syntax** [nekomaster1000/Infernal-Expansion#296]
im currently running 2.3.1 in this pack
https://www.curseforge.com/minecraft/modpacks/chosencraft
but i just tested the newest version which said it had its config files fixed and it increases my client tick like crazy :-/

**Comment by SwanX1** [comment]
The tick speed is definitely not affected by us, we haven't changed anything that even theoretically could affect the client tick speed. Only textures and configs not generating (affects only startup) have been changed between 2.3.1 and 2.3.2.
