### ISSUE TITLE
Glowstone canyon generates in the overworld

### ISSUE THREAD

**Issue by DaSentientToaster** [nekomaster1000/Infernal-Expansion#299]
**Describe the Bug:**
I installed the infernal expansion mod with environmental and other mods and the marsh biome from environmental got replaced with the glowstone canyon

**How to Reproduce:**
im not sure how to reproduce it but i think it would be installing infernal expansion over an already made world with the environmental mod

**Expected Behavior:**
 expected the biome generating in the nether and not in the overworld 

**Screenshots:**
![image](https://user-images.githubusercontent.com/92065150/137036130-ec79fa76-e7d2-45e7-b1c1-de5bb2e20437.png)

**Version Information:**
 - Operating System:
 - Mod Version: 2.3.2
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.0
 - Other mods that were running when the crash happened:
 abnormals_core-1.16.5-3.2.0.jar
 
 additional_lights-1.16.4-2.1.3.jar

 AdvancementPlaques-1.16.5-1.4.0.jar

 antiqueatlas-6.0.1-forge-mc1.16.5.jar

 antiquewaystones-1.3.jar

 Aquaculture-1.16.5-2.1.21.jar

 architectury-1.22.32-forge.jar

 areas_1.16.5-2.8.jar

 ars_nouveau-1.16.5-1.23.11.jar

 Artifacts-1.16.5-2.10.0.jar

 astikorcarts-1.16.5-1.1.1.jar

 atmospheric-1.16.5-3.1.0.jar

 AutoRegLib-1.6-49.jar

 backpacked-1.10.1-1.16.3.jar

 BannerAdditions-1.16.5-1.5.1.jar

 betterweather-2.0.1.jar

 bonetoslime-1.16.4-1.2.jar

 Bountiful-1.16.4-3.3.1.jar

 Buddycards-1.16.5-2.5.0.jar

 caelus-forge-1.16.5-2.1.3.1.jar

 carryon-1.16.5-1.15.5.15.jar

 citadel-1.8.1-1.16.5.jar

 cloth-config-4.11.26-forge.jar

 collective-1.16.5-2.64.jar

 colytra-forge-1.16.5-5.1.1.1.jar

 comforts-forge-1.16.5-4.0.1.3.jar

 corpse-1.16.5-1.0.6.jar

 create-mc1.16.5_v0.3.2d.jar

 create-stuff-additions1.16.5_v1.1.4.jar

 createchunkloading-0.2.0.jar

 createdeco-1.1.0-all.jar

 CreativeCore_v2.2.1_mc1.16.5.jar

 Croptopia-1.16.4-FORGE-1.4.2.jar

 curios-forge-1.16.5-4.0.5.3.jar

 decorative_blocks-1.16.4-1.7.2.jar

 DungeonCrawl-1.16.5-2.3.2.jar

 dungeons_gear-1.16.5-3.0.17.jar

 dungeons_mobs-1.16.5-1.0.10.jar

 dungeons_plus-1.16.5-1.1.5.jar

 enhancedcelestials-2.0.8-1.16.5.jar

 environmental-1.16.5-1.1.0.jar

 expandability-2.0.1-forge.jar

 FarmersDelight-1.16.5-0.4.6.jar

 farmersdelightintegrations-1.16.5-1.2.jar

 farsight-1.4.0-1.16.5.jar

 flywheel-1.16-0.2.3.jar

 geckolib-forge-1.16.5-3.0.46.jar

 goblintraders-1.6.0-1.16.3.jar

 guardvillagers-1.16.5.1.2.6.jar

 iceandfire-2.1.9-1.16.5.jar

 Iceberg-1.16.5-1.0.8.jar

 iChunUtil-1.16.5-10.4.1.jar

 illagers_plus-1.16.4v1.6.jar

 ItemPhysic_v1.4.18_mc1.16.5.jar

 Jade-1.16.4-2.8.0.jar

 jei-1.16.5-7.7.1.121.jar

 JustEnoughResources-1.16.5-0.12.1.122.jar

 kotlinforforge-1.15.1-obf.jar

 looot-1.16.4-1.0.0.3.jar

 Mantle-1.16.5-1.6.123.jar

mining_helmet-1.16.5-2.0.1.jar

MmmMmmMmmMmm-1.16.5-1.2.0.jar

morecreatestuffs-mc1.16-1.4.1b.jar

mostructures-forge-1.2.0-1.16.5.jar

mowziesmobs-1.5.19.jar

mysticalworld-1.16.5-0.3.3.19.jar

netherportalspread_1.16.5-5.4.jar

Paraglider-1.16.5-1.3.2.2.jar

Patchouli-1.16.4-53.2.jar

Pehkui-2.4.0+1.16.5-forge.jar

personality-1.16.5-1.0.2.jar

polymorph-forge-1.16.5-0.25.jar

Quark-r2.4-316.jar

QuarkOddities-1.16.3.jar

repurposed_structures_forge-3.2.4+1.16.5.jar

selene-1.16.5-1.7.1.jar

skinned_lanterns-1.16.5-1.3.1.jar

smallships-1.16.5-1.10.1.jar

StorageDrawers-1.16.3-8.3.0.jar

structure_gel-1.16.5-1.7.7.jar

supplementaries-1.16.5-0.17.1.jar

TConstruct-1.16.5-3.1.2.265.jar

ToolBelt-1.16.5-1.16.0.jar

towers_of_the_wild-1.16.4-2.0.1.jar

twoplayersonehorse-1.16.4-2.0.2.jar

upstream-1.0.jar

Waystones_1.16.5-7.6.3.jar

workshopsofdoom-1.16.4-1.1.0.1.jar

**Additional Context:**
Installed the mod after making the world

**Comment by Dariensg** [comment]
Never install new mods, particularly ones with biome generation, into an existing world. It will, 9 times out of 10, cause issues like this one. This is not the mods fault.

**Comment by nekomaster1000** [comment]
Could you send a screenshot of the biome in the overworld, @DaSentientToaster? I'd quite like to see it.
