### ISSUE TITLE
[Suggestion] Add config options for creature behaviour

### ISSUE THREAD

**Issue by evanbones** [nekomaster1000/Infernal-Expansion#3]
It would be fantastic to be able to disable via the config embodies attacking skeletons and ghasts attacking embodies, to make soul sand valleys a little less chaotic.

**Comment by CaelWarner** [comment]
In release 1.1 we have a config file that allows you to disable any mob behaviours that you like. The config file is in saves/"World Name"/serverconfig/infernalexp-server.toml
