### ISSUE TITLE
[1.16.5] About Infernal-Expansion run in Hybrid Server have a bug

### ISSUE THREAD

**Issue by Kotori0629** [nekomaster1000/Infernal-Expansion#303]
Install Infernal-Expansion mod and ProtocolLib plugin, error log:

https://paste.loliidc.cn/?094ed057ae462bf3#HyFLhirw29FK2U3AUZf53ZPGo12bbPsxrGSNSEC5dzZQ

**Please do not mix the server class with the client class in the fireTypeAccess class. Causes MixinEntity to crash**

**Comment by SwanX1** [comment]
Your paste link doesn't work. Nevertheless, you don't seem to be running a forge server, we don't support other server software.
