### ISSUE TITLE
forge server on aternos doesnt start with the infernal expansion mod

### ISSUE THREAD

**Issue by RealGamesTV** [nekomaster1000/Infernal-Expansion#305]
forge server version 36.2.0 and 36.8.0 on aternos doesnt start with the infernal expansion mod. it always chrashes while starting. It is maybe caused by aternos

how to reproduce it:
make a forge server on aternos with version 36.2.0 or 36.2.8. then add the infernal expansion mod to the server (version 2.3.2) and try to start the server.

**Comment by SwanX1** [comment]
i think you forgot to fill out the form buddy

**Comment by SwanX1** [comment]
this doesn't conform to the form provided. please fill out the form with the corresponding information

**Comment by SwanX1** [comment]
Closing due to no response.
