### ISSUE TITLE
I am having the Exit Code 0 Error and I can't find the source of it's location. I really need y'all help!

### ISSUE THREAD

**Issue by Plebb1n** [nekomaster1000/Infernal-Expansion#306]
So here's the last log of me trying to launch my profile on CurseForge, and everytime I launch it, it load for like 2 seconds and then Game crash Exit Code 0

https://mega.nz/file/mLQFEKbY#q0uRgMlwAWkahkdaK1yzu0cLg8hcAxW0DA9yvxhN75g -> its a doc.txt of my logs cuz they're too long

(https://www.virustotal.com/gui/file/44a834a9027646cd6a887b6bcad820a68a0af8c11c1610d0cd7f81eef42d21f0?nocache=1)

Here's the link to prove that its no hack.

**Comment by SwanX1** [comment]
This is not an Infernal Expansion issue.
