### ISSUE TITLE
Crash on boot on FML 36.2.8 server

### ISSUE THREAD

**Issue by gglobensky** [nekomaster1000/Infernal-Expansion#309]
Hi, I updated your mod and it now causes a crash on my server related to minecrafts renderer.
If I remove the mod, the server starts just fine.

Here is the log:

https://pastebin.com/9QyWGakT

Thanks for the nice mod!

**Comment by caelwarner** [comment]
Unable to replicate

**Comment by caelwarner** [comment]
Just replicated. Do you have any other mods installed?

**Comment by SwanX1** [comment]
HOW DID YOU REPLICATE THE ISSUE

**Comment by caelwarner** [comment]
By running a dedicated server with Crossroads MC installed

**Comment by caelwarner** [comment]
Ultimately I think this is caused because `FireTypeAccess` is written in an unsafe way. It's an interface that gets inherited by `Entity` that has fields of type `RenderMaterial` which are client only.
