### ISSUE TITLE
Server crashed with "Tag infernalexp:planted_quartz_base_blocks used before it was bound" 

### ISSUE THREAD

**Issue by serhiicherepanov** [nekomaster1000/Infernal-Expansion#310]
**Describe the Bug:**
During the nerher chunk loading

**How to Reproduce:**
Idk

**Expected Behavior:**
No crash

**Screenshots:**
-

**Version Information:**
 - Operating System: Linux
 - Mod Version: 2.3.2
 - Minecraft Version: 1.16.5
 - Forge Version:36.2.0
 - Other mods that were running when the crash happened:

**Additional Context:**
Crash report: https://pastebin.com/31D49Wz1

**Comment by SwanX1** [comment]
Does this happen consistently? Try restarting your game.

**Comment by serhiicherepanov** [comment]
@SwanX1 it's happen each time when i walk to this location. Currently server crashes when I trying to login under the player in this chunk.

**Comment by SwanX1** [comment]
Have you tried restarting the server?

**Comment by serhiicherepanov** [comment]
@SwanX1 Yes, it restarts automatically after the crash. I removed the Roadrunner because I thinking it can cause the issue. But it does not helped. Looks like it crashes only when broken chunk will load. The one more report https://pastebin.com/J3yPWdtS
