### ISSUE TITLE
Smooth Glowstone Slab doesn't emit light

### ISSUE THREAD

**Issue by hikuikuma** [nekomaster1000/Infernal-Expansion#316]
**Describe the Bug:**
When I put a Smooth Glowstone Slab on the ground, it doesn't emit any light, although the whole block gives off good light.

**Expected Behavior:**
I thought I could use the slabs as a light source for platforms composed of slabs.

**Screenshots:**
[Screenshot 1](https://i.imgur.com/Qa6xw8j.png)

**Version Information:**
 - Operating System: Windows 10 21H1 (19043.1348)
 - Mod Version: 2.3.2-beta.1
 - Minecraft Version: 1.17.1
 - Forge Version: 37.0.108

**Comment by caelwarner** [comment]
This is due to vanilla's lighting system and therefore there is nothing we can do about this.
