### ISSUE TITLE
can't summon shroomloin with commands

### ISSUE THREAD

**Issue by veccyboi** [nekomaster1000/Infernal-Expansion#318]
### Describe the Bug

i'm playing on forge 36.2.2
my mods folder:
![image](https://user-images.githubusercontent.com/85643556/145744179-dccbce0c-39ce-4766-8fca-e1ee9ef03f08.png)

whenever i try to summon a shroomloin with commands, it gives me an "Unable to summon entity" error message.
i'm on 2.4.0 for 1.16.5

### Reproduction Steps

1. get a command block or type "/summon infernalexp:shroomloin" into chat and try to excecute the command
2. command returns an unable to summon error
3.
...

### Expected Result

shroomloin would be summoned

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/85643556/145744276-0e9f35e6-02b7-4b09-a2c4-28df4772c2c0.png)

### Operating System

10

### Mod Version

2.4.0

### Minecraft Version

1.16.5

### Forge Version

36.2.2

**Comment by Dariensg** [comment]
I don’t remember the formatting exactly, and don’t have access to my computer right this instant, but you need to give a Shroomloin NBT data for what type it should be when summoning through a command. The format is something along the lines of `/summon infernalexp:shroomloin {ShroomloinType:[infernalexp:crimson]}` or something similar to that. I will update with exact formatting once I can get on my computer! Let me know if you figure it out with this information!

**Comment by SwanX1** [comment]
> The format is something along the lines of `/summon infernalexp:shroomloin {ShroomloinType:[infernalexp:crimson]}` or something similar to that.

Yes, you must specify a type of shroomloin when you summon it. The default is `{ShroomloinType:"infernalexp:crimson"}`
