### ISSUE TITLE
It Rains in Glowstone Canyon

### ISSUE THREAD

**Issue by LudoCrypt** [nekomaster1000/Infernal-Expansion#324]
### Describe the Bug

it rains in the Glowstone Canyon

### Reproduction Steps

1. Go to Glowstone Canyon
2. wait
3.
...

### Expected Result

Not rain

### Screenshots and Videos

https://cdn.discordapp.com/attachments/726915171074834753/934461754719756389/unknown.png

### Operating System

Windows 10

### Mod Version

2.4.0

### Minecraft Version

1.17.1

### Forge Version

37.1.1

### Other Mods

none

### Additional Context

happens in 1.16 & 1.17

**Comment by interacsion** [comment]
is this problem solved? I can't manage to recreate it. if its not solved, I would like to work on fixing that.

**Comment by Dariensg** [comment]
Nobody has committed a solution yet, but we literally have to change like 4 letters in the code to fix it, so it should get done fairly soon!

**Comment by caelwarner** [comment]
Fixed by 97fbd5c7c7e8e08880eea650e6f9d70b8dbd121c
