### ISSUE TITLE
Crash in glowstone canyon, FlyingMovementController cannot be cast to BlindsightEntity$MoveHelperController

### ISSUE THREAD

**Issue by Jetpack-Cat** [nekomaster1000/Infernal-Expansion#329]
### Describe the Bug

Running around the glowstone canyon, sudden crash

https://gist.github.com/Jetpack-Cat/1542ff778d8e2669263f0f465c5525b4

### Reproduction Steps

run around nether in glowstone canyon

### Expected Result

not to crash randomly

### Operating System

Windows 10

### Mod Version

2.4.0

### Minecraft Version

1.16.5

### Forge Version

36.2.33

### Other Mods

check crash log

### Additional Context

none

**Comment by Jetpack-Cat** [comment]
I updated forge to 36.2.35 and it still happens

**Comment by SwanX1** [comment]
Context I got from the crash report: Blindsight is riding a parrot, then the blindsight is trying to get the blindsight's movement controller helper, but gets a parrot movement controller helper which then is throwing a cast error.

**Comment by Dariensg** [comment]
Context helps a lot! I believe when an entity is riding another entity, the rider's AI is used for behavior, but the vehicle's navigation is used for the actual movement. Therefore, the Blindsight is trying to use its usual HopGoal for AI, but that requires a Blindsight MoveHelperController. Should be an easy fix, but would potentially remove all movement from Blindsights riding other entities. I'll leave this note here for when someone has a chance to fix it!

**Comment by Jetpack-Cat** [comment]
Ah, it's improved mobs. It makes mobs ride parrots to get to you if the entity has no way to reach you. eg if you're in a tree.
I added the blindsight entity to the blacklist in my config..
