### ISSUE TITLE
Glowsquitos take fall damage

### ISSUE THREAD

**Issue by caelwarner** [nekomaster1000/Infernal-Expansion#330]
Glowsquito's are taking fall damage when they certainly aren't supposed to. Found on `1.18` but could be present on `1.17` and `1.16`.

Credit to **ClephLeSDF#6951** for discovering this issue.

**Comment by DarthCaesium** [comment]
I know it is useless for me to rely on memory alone, but I swear I remember Glowsquitos taking fall damage in 1.16.5 as well.

**Comment by caelwarner** [comment]
The issue is not present in `1.16`, however it is present in `1.17` and `1.18`
