### ISSUE TITLE
Glowstone Canyon spawn rate seems abnormally low when using Biomes O' Plenty and Terrablender in 1.18.2

### ISSUE THREAD

**Issue by DarthCaesium** [nekomaster1000/Infernal-Expansion#333]
### Describe the Bug

The Glowstone Canyon biome seems to spawn much more rarely than intended when using Biomes O' Plenty and Terrablender.

### Reproduction Steps

Search for the biome in the Nether.

### Expected Result

The biome will generate much more commonly.

### Operating System

Linux Mint 20.3

### Mod Version

2.5 Beta 1

### Minecraft Version

1.18.2

### Forge Version

40.1.30

### Other Mods

Biomes O' Plenty, Terrablender.

**Comment by caelwarner** [comment]
While it might seem low, I think it's rather on par with the spawn rate of every other biome in the nether. When you add more biomes each one is going to show up less frequently.
