### ISSUE TITLE
Fungus caps spawn way too much

### ISSUE THREAD

**Issue by dabomb6405** [nekomaster1000/Infernal-Expansion#336]
### Describe the Bug

In the crimson and warped forests, fungus caps spawn all over the place, which I'm pretty sure isn't intentional since I remember them spawning at the same frequency as pumpkins in the 1.16 version

### Reproduction Steps

1. go to the nether
2. find crimson or warped forest
3. fungus cap galore

### Expected Result

Fungus caps should be spawning uncommonly in patches like pumpkins.

### Screenshots and Videos

![2022-06-02_11 01 29](https://user-images.githubusercontent.com/66895105/171697615-a6b1a02b-97d8-4caa-b8f7-f4dd91ed7489.png)

### Operating System

Windows 10

### Mod Version

2.5.0 Beta 1

### Minecraft Version

1.18.2

### Forge Version

40.1.25

**Comment by caelwarner** [comment]
Fixed by 6bb72db
