### ISSUE TITLE
Bug (1.18 beta) - Spirit eyes do not have a recipe.

### ISSUE THREAD

**Issue by Bonniethebunny-hub** [nekomaster1000/Infernal-Expansion#338]
### Describe the Bug

Spirit eyes are currently uncraftable.

### Reproduction Steps

Try to craft the eye.

### Expected Result

Dont craf the eye.

### Operating System

Windows 10

### Mod Version

2.4.0

### Minecraft Version

1.17.1

### Forge Version

1111

**Comment by nekomaster1000** [comment]
Fixed in commit [607a68b](https://github.com/infernalexp/Infernal-Expansion/commit/607a68b6eda2b2e20b94fa272efcab01459a911b) 👍
