### ISSUE TITLE
The Nether ceiling for the Glowstone Canyon is not made of Bedrock.

### ISSUE THREAD

**Issue by DarthCaesium** [nekomaster1000/Infernal-Expansion#339]
### Describe the Bug

The Nether ceiling for the Glowstone Canyon is not made of Bedrock.

### Reproduction Steps

Search for the biome in the Nether and go to its ceiling.

### Expected Result

The biome will have a Bedrock ceiling.

### Screenshots and Videos

![2022-06-02_20 30 20](https://user-images.githubusercontent.com/85497136/171836865-67118cf8-7483-4b6b-9739-70e49a10c0d9.png)

### Operating System

Linux Mint 20.3

### Mod Version

2.5 Beta 1

### Minecraft Version

1.18.2

### Forge Version

40.1.30

**Comment by DarthCaesium** [comment]
Edit: the same applies for the Nether Bedrock floor.

![2022-06-03_12 23 08](https://user-images.githubusercontent.com/85497136/171845979-b46af8f6-35a3-4bd3-bf6d-a6fe268df625.png)

**Comment by caelwarner** [comment]
I can't replicate this. You had no other mods loaded, right?

**Comment by DarthCaesium** [comment]
I am also using Terrablender and Biomes O' Plenty.
