### ISSUE TITLE
Item does not disappear with Glowsilk Bow charging state

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#341]
### Describe the Bug

When you are charging a Glowsilk bow, the item that you are holding in your other hand does not disappear compared to charging with a regular bow.

### Reproduction Steps

1. Obtain a Glowsilk Bow in the offhand slot/main slot
2. Hold any item in the offhand slot/main slot
3. Charge the Glowsilk Bow
4. Compare the difference with a regular bow

### Expected Result

The item in the opposite hand should lower to the bottom of the screen and disappear.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/49106149/171994896-e0e5677b-9ffc-48b3-aa58-33e730acb795.png)
![image](https://user-images.githubusercontent.com/49106149/171994904-83491835-3300-4442-8c99-320dbdb2d552.png)

### Operating System

Windows 10

### Mod Version

Beta 2.5.0-1

### Minecraft Version

1.18.2

### Forge Version

40.1.31

### Other Mods

N/A

**Comment by caelwarner** [comment]
Present on `1.17`
