### ISSUE TITLE
Glowsilk Bow does not zoom camera

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#342]
### Describe the Bug

When you charge a Glowsilk Bow, it does not zoom in the camera whilst charging the bow fully

### Reproduction Steps

1. Get a Glowsilk Bow
2. Charge the Bow like you would with a regular Bow
3. Get a regular bow and compare the difference

### Expected Result

The bow should utilize the camera zoom-in, much like the regular bow

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/49106149/171995012-b5dc3a92-8c12-4ee1-8c41-907b69c9293c.png)
With no zoom
![image](https://user-images.githubusercontent.com/49106149/171995134-08368b4d-fca1-4b4d-a598-8a7bc08bfdcd.png)
With zoom

### Operating System

Windows 10

### Mod Version

Beta 2.5.0-1

### Minecraft Version

1.18.2

### Forge Version

40.1.31

### Other Mods

N/A

**Comment by caelwarner** [comment]
Present on `1.17`
