### ISSUE TITLE
Unable to create Luminance and Infection potions

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#344]
### Describe the Bug

The potions this mod adds, such as Potion of Luminance and Infection, cannot be created. When trying to insert the item into the brewing stand, it does not allow you to input the item.

### Reproduction Steps

1. Get an Awkward potion
2. Try to mix it with Moth Dust or an Ascus Bomb

### Expected Result

The pre-mentioned items should mix into the Luminance and Infection Potions respectively

### Operating System

Windows 10

### Mod Version

Beta 2.5.0-1

### Minecraft Version

1.18.2

### Forge Version

40.1.31

### Other Mods

N/a

**Comment by caelwarner** [comment]
I'm able to create both Infection and Luminance potions with a brewing stand and the recipes you mentioned above. Anything I might be missing?

**Comment by caelwarner** [comment]
You were using blaze powder in the brewing stand?

**Comment by neoNoteCoder** [comment]
That’s really weird, since I wasn’t able to create those potions at all before. I’ll see if I can record footage it as soon as possible, but for some reason it just didn’t work for me. I was indeed using blaze powder as well.

**Comment by neoNoteCoder** [comment]
https://user-images.githubusercontent.com/49106149/172051447-c4b2a869-f0af-48cb-8e0b-0eca95affe53.mp4


As you can see in the video, I brew an awkward potion correctly. However, when it comes to adding the ingredients for infection and luminance potions, they cannot be placed in the slot required to make the potions.

**Comment by caelwarner** [comment]
Only happens in production environments. Issue is due to using reflection to register brewing recipes
