### ISSUE TITLE
incompatibility with the incendum datapack

### ISSUE THREAD

**Issue by kuba26038** [nekomaster1000/Infernal-Expansion#346]
### Describe the Bug

i'm not 100% sure if it's normal but if not, the glowstone chasm biome doesn't generate if the incendum datapack is installed.

### Reproduction Steps

1. install both the 1.18.2 infernal expansion beta and the newest version of incendum
2. in the nether use the locate function to see if the glowstone chasm generated
3. it didn't generate
...

### Expected Result

i'm pretty sure both incendum biomes and the glowstone chasm biome should generate in a single world

### Operating System

Windows 10

### Mod Version

Beta 2.5.0-1

### Minecraft Version

1.18.2

### Forge Version

40.1.31

**Comment by caelwarner** [comment]
I feel like we've always had compatibility issues with the Incendium datapack, though I don't remember. Did it work in 1.16?

**Comment by JKaiya** [comment]
That more of incendium's side, as their mod overwrites other mods, you can use amplified nether though as it does not overwrite other nether biome mods

**Comment by Dariensg** [comment]
I totally forgot to close this issue. There are instructions on our CurseForge page on how to get Infernal Expansion and Incendium running together. It can be slightly advanced, but we described the basic process on CurseForge. Closing this now since it is resolved.
