### ISSUE TITLE
Mod load error, server keeps crashing.

### ISSUE THREAD

**Issue by LordNuroch** [nekomaster1000/Infernal-Expansion#348]
### Describe the Bug

My server keeps crashing due to a Mod loading error.:
Infernal Expansion (infernalexp) encountered an error during the common_setup event phase
		java.lang.ArrayIndexOutOfBoundsException: Index 512 out of bounds for length 257

### Reproduction Steps

1. Have mod on server
2. Try to start Server
3.
...

### Expected Result

I expect the server to start up properly

### Screenshots and Videos

[crash-2022-06-06_06.20.40-fml.txt](https://github.com/infernalexp/Infernal-Expansion/files/8842370/crash-2022-06-06_06.20.40-fml.txt)

### Operating System

Linux

### Mod Version

2.4.0

### Minecraft Version

1.16.5

### Forge Version

1.16.5-36.2.30

### Other Mods

There's a ton of mods, they are listed in the attached crash log.

**Comment by caelwarner** [comment]
Does this crash still happen if Infernal Expansion is the only mod being loaded?
