### ISSUE TITLE
Infection half-heart overlay displayed incorrectly

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#349]
### Describe the Bug

When you lose health whilst having infection on you, if you have any instance of half-hearts in your health bar, the health GUI will display the regular heart rather than the infection heart

### Reproduction Steps

1. Take damage with the Infection effect

### Expected Result

The half heart should not show the regular heart, but rather the infection heart.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/49106149/172209737-1fe90493-0353-40ce-969d-5bda18397630.png)

### Operating System

Windows 10

### Mod Version

Beta 2.5.0-1

### Minecraft Version

1.18.2

### Forge Version

40.1.31

### Other Mods

N/a

### Additional Context

N/a

**Comment by caelwarner** [comment]
Fixed by b29332b7c1b2156742522557570a1d591a987d30
