### ISSUE TITLE
Crash on launch of client

### ISSUE THREAD

**Issue by xmsteele23** [nekomaster1000/Infernal-Expansion#350]
### Describe the Bug

only happened once out of several successful startups, but figured it best to report it. [https://gist.github.com/xmsteele23/ca56454257d39dc516d0ceedc19e0354](https://gist.github.com/xmsteele23/ca56454257d39dc516d0ceedc19e0354) crash report
[https://gist.github.com/xmsteele23/ba5550e149ab914804c93edf24d7a6a4](https://gist.github.com/xmsteele23/ba5550e149ab914804c93edf24d7a6a4) debug log

### Reproduction Steps

1.
2.
3.
...
use my mods and load up the beta a couple of times

### Expected Result

the game to launch.

### Operating System

Windows 10 Pro

### Mod Version

Beta 2.5.0-1

### Minecraft Version

1.18.2

### Forge Version

forge-1.18.2-40.1.31

### Other Mods

all the yungs mods
terralith terrablender
biomes u go
integrated structures and dungeons

**Comment by caelwarner** [comment]
Same crash as #348

**Comment by caelwarner** [comment]
Just to confirm, this crash has only ever happened once?
