### ISSUE TITLE
Mass spawning of Basalt Giants at Nether Fortress

### ISSUE THREAD

**Issue by neoNoteCoder** [nekomaster1000/Infernal-Expansion#352]
### Describe the Bug

Whilst the player is venturing through a Nether Fortress that is inside or nearby the Basalt Deltas, large groups of Basalt Giants will overwhelm the entire area of the fortress

### Reproduction Steps

Find a Nether Fortress that is nearby a Basalt Deltas biome

### Expected Result

Maybe, just maybe a massive lack of Basalt Giants to swarm the Fortress?

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/49106149/173429071-de1fc771-5f6d-4ef3-b63d-a0607ff54694.png)

### Operating System

Windows 10

### Mod Version

Beta 2.5.0-1

### Minecraft Version

1.18.2

### Forge Version

40.1.31

### Other Mods

![image](https://user-images.githubusercontent.com/49106149/173429438-48e109ed-d5bd-4a23-956e-4647e356bfb2.png)
![image](https://user-images.githubusercontent.com/49106149/173429455-e3591282-12c6-4c26-ade4-99a7b57821ec.png)
![image](https://user-images.githubusercontent.com/49106149/173429478-604566c5-ee6e-4e92-80c8-4b357595ed5d.png)

### Additional Context

Coordinates: -280 / 76 / 165
Seed: 7582195160449071942

**Comment by nekomaster1000** [comment]
Could you provide the world seed and coordinates where this happened please? Thanks!

**Comment by Jellybubble** [comment]
>

**Comment by neoNoteCoder** [comment]
Issue has been updated with world seed and coordinate info.

**Comment by caelwarner** [comment]
Fixed by 73aee63ea6516ce19f7d9891d54ed9f1574d1282
