### ISSUE TITLE
[1.16.5] Server crash on startup with Crossroads

### ISSUE THREAD

**Issue by Diversion98** [nekomaster1000/Infernal-Expansion#366]
### Describe the Bug

The server crashes when I start a fresh new server.
On a client, the mods works just fine.

When I delete Crossroads 2.6.5 from the server and keep Essentials 2.11.1, the server starts just fine.
When I infernal-expansion 2.4.0 and keep Crossroads and Essentials, the server starts just fine.

### Reproduction Steps

1. add the folowing mods to a minecraft forge 36.2.35 server:

    - Crossroads 2.6.5
    - Essentials 2.11.1
    - Infernal Expansion 2.4.0
    
2. Start the server and watch it fail

3. Delete Crossroads or Infernal Expansion

4. Start the server and watch it succeed

### Expected Result

compatibility between the 2 mods so it can start on a server (client works just fine)

### Operating System

Windows 11

### Mod Version

2.4.0

### Minecraft Version

1.16.5

### Forge Version

36.2.35

### Other Mods

Crossroads 2.6.5
Essentials 2.11.1

### Additional Context

I also made an issue on their github: https://github.com/Crossroads-Development/Crossroads/issues/209

[debug.log](https://github.com/infernalstudios/Infernal-Expansion/files/9034224/debug.log)
[latest.log](https://github.com/infernalstudios/Infernal-Expansion/files/9034225/latest.log)

**Comment by Dariensg** [comment]
You are using an outdated version of Infernal Expansion. This bug has been fixed in 2.5.0. Please update to the latest version.
