### ISSUE TITLE
Crash when entering the nether

### ISSUE THREAD

**Issue by PhoenixKnight3** [nekomaster1000/Infernal-Expansion#368]
### Describe the Bug

The game will crash when entering the nether when you have Infernal Expansion, Mining Master and Big Brain all installed at the same time.

### Reproduction Steps

1. Install Infernal Expansion, Mining Master and Big Brain
2. Create a world and enter the Nether

### Expected Result

The game will crash

### Operating System

Windows 10

### Mod Version

Beta 2.5.0-1

### Minecraft Version

1.18.2

### Forge Version

41.0.63

### Other Mods

Big Brain and Mining master

### Additional Context

The issue takes place in 1.19 but the Minecraft version picker does not have it as an option so I had to put it as 1.18.2

**Comment by Dariensg** [comment]
Please provide a crash log! This may be the same issue as #367 which we’re looking into, but I won’t know without a crash log. Also, you seem to have put in the wrong mod version as Beta 2.5.0-1 doesn’t exist for 1.19.
