### ISSUE TITLE
Glowsilk bow inaccuracy and hitbox misbehaviour due to projectile speed not considering vanilla caps

### ISSUE THREAD

**Issue by NighthowlerStudios** [nekomaster1000/Infernal-Expansion#371]
### Describe the Bug

A bug was discovered in vanilla during development of my other mods that clearly demonstrates vanilla minecraft projectile motion calculation actually caps at a speed of 4.  this is why your bow is "snapping to angle".  you need to implement a mixin and custom motion packet in order to completely get rid of the speed capper in the motion methodology of your projectile.  an example can be found in the codebase of Kaleidio's Guns.

It has been recommended by Forge themselves for years to always implement a custom system for high speed projectiles

### Reproduction Steps

1. shoot an infernal expansion bow
2. watch the projectile "snap to" 10 or so degrees in angle
3. sometimes the hitbox will phase directly through an enemy because of this

### Expected Result

don't snap to angle, calculate projectile motion manually.

### Operating System

Windows 10 21H2

### Mod Version

any

### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Additional Context

the vanilla method you will want to mixin and change is the network and mixin packages of the following mod codebase.  ignore any variables not relevant to your mod:

https://github.com/Exploding-Creeper/GunsWithoutRoses/commit/d5f7131fbd02e42dd8fc716459deaa480ea7dda7

**Comment by Dariensg** [comment]
Thank you for reporting this and giving such clear examples of a fix! We will absolutely look into this and work on a fix!

**Comment by ArkVeil** [comment]
I want to add that this issue also occurs on the 1.18.2 version as well. I also noticed the bug occurs depending on what angle you are firing the bow. Fire toward any of the cardinal directions (0, 90, 180, -90) and the bow fires as straight as you'd expect. If you angle toward any diagonal, the bug begins to appear, with increasing severity the further you are from a cardinal direction.

**Comment by NighthowlerStudios** [comment]
This bug can be fixed by installing the third party mod Fast Projectile Fix, which uses a catch-all mod compatible mixin to force arrows to use a motion boundary breaking compatible mixined networking packet.  However for the sake of consideration to the devs of this mod I'm leaving the issue open for them to close if they wish not to focus any further on the bug

**Comment by Mikzoru** [comment]
> This bug can be fixed by installing the third party mod Fast Projectile Fix, which uses a catch-all mod compatible mixin to force arrows to use a motion boundary breaking compatible mixined networking packet. However for the sake of consideration to the devs of this mod I'm leaving the issue open for them to close if they wish not to focus any further on the bug

Fast Projectile Fix unfortunately does not exist for any version besides 1.16 :(
