### ISSUE TITLE
Whip occasionally does not swing

### ISSUE THREAD

**Issue by juicebin** [nekomaster1000/Infernal-Expansion#372]
### Describe the Bug

Occasionally, whips will be unable to swing. On release, it will not damage the entity, will not make a whip sound, and will not animate the texture. It just charges.

I am making this report about _both_ whips, although right _now_ it is just the Kinetic Tongue Whip. I vividly remember it not working last night for the Blindsight Tongue Whip, but now that it's working I am second-guessing myself 😓

However, both whips have worked before. I'm not sure by what circumstances.

### Reproduction Steps

This is the best I can give you:
1. Start a creative world
2. Grab either the Kinetic Tongue Whip or Blindsight Tongue Whip (or both)
3. Charge the whip all the way and release

### Expected Result

From what I have gathered and experience with the whip: it should have a crack-back animation, make a popping noise on release, and hit the targeted enemy.

### Screenshots and Videos

Sound is not included due to how it was recorded. Sorry for the poor resolution, Loom was being funky. This video will likely be removed within like a month, by the way! Will re-upload it by then if entirely necessary.

The video demonstrates the Kinetic Tongue Whip _not_ working as intended, and the Blindsight Tongue Whip working as intended.

Let me know if this link doesn't work!

https://www.loom.com/share/a4e472484cc54f23aca4a4d7d23d4f3b

### Operating System

Windows 11

### Mod Version

2.5.0

### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Other Mods

[modlist.txt](https://github.com/infernalstudios/Infernal-Expansion/files/9095965/modlist.txt)

**Comment by caelwarner** [comment]
Hopefully that fix solves this issue. I believe the issue was caused when there was small desync between the client and the server where the client would get a little bit ahead of the server causing the whip to prematurely end its attack. This issue basically never happened if the game was running perfectly smoothly. But with just a little bit of lag (often a pretty unperceptible amount) this issue would start to show up.
