### ISSUE TITLE
Blindsight Whiptongue Crashes Servers 1.16.5 Upon Usage

### ISSUE THREAD

**Issue by TheRealZonko** [nekomaster1000/Infernal-Expansion#375]
### Describe the Bug

Whenever I use the Whiptongue (in creative at least) I crash the entire server and make it restart.  This is in Forge 1.16.5.  It should be easily replicable.

### Reproduction Steps

1.  Join server
2. 2.  Use Whiptongue

### Expected Result

Server crashes

### Operating System

Windows 10

### Mod Version

2.5.0

### Minecraft Version

1.16.5

### Forge Version

36.2.35

**Comment by Dariensg** [comment]
Please supply a crash report.

**Comment by TheRealZonko** [comment]
Here you go, the report is attached to this email.  Sorry I thought it
would be pretty easy to replicate but you def need to know if there are
other mods on.  I was only using Infernal Expansion.  Hope this helps

Attached file (added by moderator): https://paste.gg/7a9bc94681a0486390b595b428b01951
