### ISSUE TITLE
No glow shroom variant of shroomloin (missing quark compat) 

### ISSUE THREAD

**Issue by RealGamesTV** [nekomaster1000/Infernal-Expansion#379]
### Describe the Bug

There is no glow shroom (item from quark mod) variant of shroomloin. On mc version 1.16 there was one, but on the newer versions not. I tested it on mc versions 1.18 and 1.19 ( on these versions it didn't work). 

### Reproduction Steps

1.feed a glow shroom from the quark mod to a shroomloin
2.the shroomloin won't change the variant
3.
...

### Expected Result

Shroomloin variant

### Operating System

Windows 10

### Mod Version

2.5.1

### Minecraft Version

1.19

### Forge Version

41.0.63

### Additional Context

It also doesn't work on mc 1.18. 2 version

**Comment by nekomaster1000** [comment]
Just had a look, at it seems for whatever reason that Quark's Glow Shroom item has been refactored in code from 'glowshroom', which is what we used, to 'glow_shroom'. Should be an easy fix! 

@RealGamesTV If you have the time, could you be supremely cool and crosscheck the functionality of all the _other_ Shroomloin variant textures with the rest of the mods we added compat to? (That are on 1.18, of course.)
Here's the list of mods:
"habitat",    
"darkerdepths"
"quark",          
"undergarden",
"twist",      
"endergetic", 
"shroomed",       
"byg",        
"biomesoplenty"

If you can't, no worries, but if you can, thanks a bunch in advance!

**Comment by SwanX1** [comment]
Fixed in bd0211ff333f03e8ce52486d8944d9f0a981cce4 for 1.19
