### ISSUE TITLE
Enchanced mushrooms compatibility not working 1.18

### ISSUE THREAD

**Issue by TheCebulaShark** [nekomaster1000/Infernal-Expansion#380]
### Describe the Bug

In glowshroom canyom spawns regular brown mushrooms instead of luminous one

### Reproduction Steps

-

### Expected Result

Glowshroom hanging stems instead of regular brow

### Operating System

Windows 10

### Mod Version

2.5.1

### Minecraft Version

1.18.2

### Forge Version

40.1.54

**Comment by caelwarner** [comment]
The mushrooms on the ceiling of the Glowstone Canyon are intended to be brown. With Enhanced Mushrooms installed it replaces the vanilla mushroom stem with the brown mushroom stem from Enhanced Mushrooms.
