### ISSUE TITLE
Game Crashing on Loadup Forge 1.19

### ISSUE THREAD

**Issue by jackboi03** [nekomaster1000/Infernal-Expansion#381]
When I start my Modpack, the game loads a split second, and then crashes. Here you can find the full crash log:

[crash-log-infernal-expansion.txt](https://paste.gg/34109a4860c640e883306f4c36dd5681)
I know that it is Infernal Expansion, because I tested every Mod, and the game works fine with every other mod i am using.

**Comment by SwanX1** [comment]
Infernal Expansion isn't compatible with Forge 41.0.64+ yet.

**Comment by jackboi03** [comment]
Ah okay, thanks for the quick answer! Is there an ETA for that?

**Comment by SwanX1** [comment]
Within a week, most likely, but that isn't set in stone.

**Comment by jackboi03** [comment]
Okay, thanks a lot. Have a great night/day whatever time it is for you xD

**Comment by SwanX1** [comment]
Keep the issue open, we'll close it once it's fixed.

**Comment by jackboi03** [comment]
Okay

**Comment by SalemRobin** [comment]
[crash-2022-07-30_01.09.18-client.txt](https://paste.gg/4348fbf661db4ca4b25e5806ba3d35ec)
Crash report for same issue if it would be of use. Disregard if it isn't lol

**Comment by SwanX1** [comment]
Fixed in d9652960d5d70a49add00c441ddad615cdc9e2ff
