### ISSUE TITLE
Volines ignore magma cream held

### ISSUE THREAD

**Issue by Saereth** [nekomaster1000/Infernal-Expansion#383]
### Describe the Bug

The wiki seems to imply volines will ignore you if you hold a magma cream, this does not currently work

### Reproduction Steps

1. Hold a magma cream
2. Walk next to a voline
3. proceed to be ankle bitten

### Expected Result

Ankles to be left in tact

### Operating System

I use Arch, btw

### Mod Version

2.5.1

### Minecraft Version

1.18.2

### Forge Version

40.1.73

**Comment by Dariensg** [comment]
So that's actually a mistake on the wiki. That was never meant to be a mechanic, but the person who wrote the wiki thought it was. Sorry about the confusion!
