### ISSUE TITLE
1.19.2 crash

### ISSUE THREAD

**Issue by gohkenytp** [nekomaster1000/Infernal-Expansion#387]
### Describe the Bug

I noticed that this is mod is incompatible for Forge 1.19.2

### Reproduction Steps

1. Fix that bug that is incompatible to Alex's Mobs

### Expected Result

Port it to Forge 1.19.2

### Operating System

Windows 11

### Mod Version

2.5.1

### Minecraft Version

1.19

### Forge Version

43.1.25

### Other Mods

Alex's mobs

**Comment by Dariensg** [comment]
You are correct. This is not a 1.19.2 mod. The CurseForge page should say 1.19 and 1.19.1; that is accurate.

**Comment by gohkenytp** [comment]
Well, is it going to be ported to 1.19.2 yet?

**Comment by caelwarner** [comment]
Good news! Infernal Expansion has now been ported to 1.19.2. Get it at [https://www.curseforge.com/minecraft/mc-mods/infernal-expansion/files/4002091](https://www.curseforge.com/minecraft/mc-mods/infernal-expansion/files/4002091)
