### ISSUE TITLE
Mod crashes on dedicated server due to trying to load a GUI.

### ISSUE THREAD

**Issue by SwanX1** [nekomaster1000/Infernal-Expansion#39]
**Describe the bug**
Infernal Expansion crashes on dedicated server.

**To Reproduce**
Launch a Minecraft Forge server with the mod installed

**Expected behavior**
The mod should ignore the GUI when launched on server.

**Version Information**
 - Operating System: GNU/Linux (Ubuntu Server 20.04)
 - Mod Version: 2.0.0 development version.
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.2

**Additional context**
Crash report: [crash-2021-03-24_11.17.57-fml.txt](https://gist.github.com/SwanX1/925c45fdcc94c8b268c0f3b2383e62aa#file-crash-2021-03-24_11-17-57-fml-txt)

**Comment by SwanX1** [comment]
Update: Removing the entire `com.nekomaster1000.infernalexp.config.gui` package fixes the problem, so the problem is in there

**Comment by caelwarner** [comment]
Closed by https://github.com/infernalexp/Infernal-Expansion/commit/fd3df6bd8bd0f1e4dae2933ccb7fa386c19eeaab
