### ISSUE TITLE
1.18.2 Quark glow shroom not applying to Shroomloins

### ISSUE THREAD

**Issue by Armokthespideroverlord** [nekomaster1000/Infernal-Expansion#392]
### Describe the Bug

For whatever reason, trying to right-click Shroomloins with quark's glow shroom does absolutely nothing, the glow shroom isn't consumed and the Shroomlion retains the same texture and behaviors as before. I thought that this mod had support for quark's glow shrooms?

### Reproduction Steps

1. Spawned a Shroomloin in creative mode.
2. Right clicked quark's glow shroom on it.
3. Nothing happens.

### Expected Result

Obviously expecting for the Shroomloin to change to reflect quark's glow shroom

### Operating System

Windows 10

### Mod Version

2.5.0

### Minecraft Version

1.18.2

### Forge Version

40.1.69

**Comment by Dariensg** [comment]
This is technically the same issue as #382. It's caused by Quark having changed the name of their glow shroom in code.

**Comment by SwanX1** [comment]
it is the same as #382
