### ISSUE TITLE
missing sounds and broken recipe

### ISSUE THREAD

**Issue by x4dr** [nekomaster1000/Infernal-Expansion#398]
### Describe the Bug

as in https://discord.com/channels/681976442220839008/906640241849430047/1029086097537499196

``[19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.skeletal_piglin.ambient [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.skeletal_piglin.hurt [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.skeletal_piglin.death [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.dwarf.ambient [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.dwarf.hurt [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.dwarf.death [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.glaw.ambient [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.glaw.hurt [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.glaw.death [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.smolt.ambient [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.smolt.hurt [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.smolt.death [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.pyrno.ambient [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.pyrno.hurt [19:29:10] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: infernalexp:entity.pyrno.death```

are probably no longer needed

also `[19:32:03] [Render thread/ERROR] [me.je.pl.va.cr.CategoryRecipeValidator/]: Recipe has no output. Infernal Expansion infernalexp:stonecutting/basalt_bricks_vertical_slab class net.minecraft.world.item.crafting.StonecutterRecipe {   Outputs:   Inputs:     net.minecraft.world.item.ItemStack: [1 basalt_bricks infernalexp:basalt_bricks]   Catalysts: }` 
is a recipe without output

### Reproduction Steps

1. install mod
2. start game
3. read log 

### Expected Result

only errors and warnings that are unexpected

### Operating System

linux 5.19.13-arch1-1

### Mod Version

2.5.0

### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Other Mods

many

**Comment by MarioSMB** [comment]
The actual item name is `infernalexp:basalt_brick_vertical_slab` incase anyone is interested in fixing this.
