### ISSUE TITLE
Crash on startup 1.16.5 Infernal expansion has failed to load correctly

### ISSUE THREAD

**Issue by Jetpack-Cat** [nekomaster1000/Infernal-Expansion#401]
### Describe the Bug

On startup, on some occasions, not every time, the game crashes
![image](https://user-images.githubusercontent.com/100042170/198887730-e8164f5d-1abc-465b-b304-4bda3d85db86.png)

### Reproduction Steps

start game

### Expected Result

to not crash

### Operating System

Windows 11

### Mod Version

2.5.0

### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Other Mods

https://www.curseforge.com/minecraft/modpacks/jetpack-cat/relations/dependencies

### Additional Context

[crash-2022-10-30_08.39.17-fml.txt](https://github.com/infernalstudios/Infernal-Expansion/files/9896208/crash-2022-10-30_08.39.17-fml.txt)

[debug.log](https://github.com/infernalstudios/Infernal-Expansion/files/9896209/debug.log)

[latest.log](https://github.com/infernalstudios/Infernal-Expansion/files/9896210/latest.log)

**Comment by caelwarner** [comment]
How frequently does the game crash? Like half the time? A quarter of the time? Only very rarely?

**Comment by caelwarner** [comment]
Just launched your modpack to try to reproduce the issue and wow! I just want to compliment how impressive the modpack is.

**Comment by caelwarner** [comment]
I was unable to reproduce the issue but I think I see what's causing it. Hopefully the fix I implemented in the above commit should fix it. The fix will be present in the next release.
