### ISSUE TITLE
Mob sounds independent of mob location respective to player

### ISSUE THREAD

**Issue by originalusername32** [nekomaster1000/Infernal-Expansion#406]
### Describe the Bug

I'm unsure of how to really describe this, but I feel like the title is pretty accurate. Essentially, the sounds of all of the mobs always sound like they're directly next to the player, irrespective of whether they truly are or not. This makes for both a very loud and disorienting experience when exploring.

I recognize the video isn't really the best example, as you can hear blazes, but I think it gets my point across.

### Reproduction Steps

1. Wait for mobs to make noise(?)

### Expected Result

Sounds to be effected by mob position relative to the player

### Screenshots and Videos

https://user-images.githubusercontent.com/116246905/205516476-c8de10b4-305d-41c0-a654-8220b8bf5550.mp4

### Operating System

Windows 10

### Mod Version

2.5.1

### Minecraft Version

1.19

### Forge Version

43.1.52

**Comment by originalusername32** [comment]
Believe I've found the cause for this - the sound files may be in stereo rather than mono.

**Comment by Dariensg** [comment]
There's a lot of sound files and I think this is probably the issue too. I have a script that will convert them all for me that we can run to fix this, so don't worry about converting them all yourself! If you want to test one or two to guarantee this is the issue, that would be great! But don't worry about doing them all as I can do that in a matter of seconds.

**Comment by originalusername32** [comment]
I actually just converted a few sounds over from a resource pack I was using from stereo to mono as it was having the same issue and that fixed it - opening the Basalt Giant ambient sound in Audacity shows that its in stereo.

Editing the ambient noise to be in mono fixed the problem, though it sounds quieter than was probably intended. Might play around with it more.
