### ISSUE TITLE
Smooth Basalt recipes get blocked

### ISSUE THREAD

**Issue by brianfreud** [nekomaster1000/Infernal-Expansion#407]
### Describe the Bug

With the change to smelting basalt, giving cobbled basalt, the vanilla recipe which would instead give smooth basalt gets replaced, and there is no alternate recipe given that would still allow the creation of smooth basalt without using something like Polymorph to change the default.

### Reproduction Steps

1.
2.
3.
...

### Expected Result

Some crafting path remaining for making smooth basalt.

### Operating System

Linux

### Mod Version

2.5.1

### Minecraft Version

1.18.2

### Forge Version

40.1.86

**Comment by riley-9054** [comment]
Can confirm this cobbled basalt recipe still exists on 1.19.2, so I'm assuming it still blocks the smooth basalt recipe, that or smooth basalt now blocks it.
Either way, this could be solved by moving the cobbled basalt recipe to the blast furnace. Plenty of other mods have furnace recipes exclusive to the blast furnace or smoker, like pendorite from Oh the Biomes You'll Go and charcoal blocks from Architect's Palette.

**Comment by MarioSMB** [comment]
Perhaps cobbled basalt should be the "cobblestone" version of basalt, in that basalt itself drops cobbled basalt and smelting it produces basalt - or by using a silk touch pickaxe.

**Comment by caelwarner** [comment]
Thank you for bringing this to our attention :) We decided to replace the cobbled basalt recipe with a simple shapeless crafting recipe requiring two basalt and giving two cobbled basalt.
