### ISSUE TITLE
[critical] Removing infernal expansion will permanently disable the nether on a world

### ISSUE THREAD

**Issue by A00826925** [nekomaster1000/Infernal-Expansion#418]
### Describe the Bug

Removing infernal expansion will remove the ability to traverse to the nether. Even deleting the nether dimension from the world will still make it inaccessible, the nether portal will continue loading endlessly and trying to force tp to the nether (i tried using telepad) and got a crash with a null pointer exception.

### Reproduction Steps

1. Create a world and nether with infernal expansion
2. close, delete infernal expansion
3. try loading nether, it will not load, even deleting the nether dimension file will not regenerate the nether.
...

### Expected Result

the nether should load, even without the infernal expansion, and more so after deleting the nether dimension, idk what file it modifies but knowing that would bring clarity to the issue

### Operating System

windows 11

### Mod Version

2.5.1

### Minecraft Version

1.19

### Forge Version

43.2.4

### Other Mods

this modpack https://beta.curseforge.com/minecraft/modpacks/better-forever

### Additional Context

i also noticed the mod makes the nether load very slowly, painful enough to make me want to get rid of it no matter what

**Comment by A00826925** [comment]
[crash-2023-02-12_17.40.41-server.txt](https://github.com/infernalstudios/Infernal-Expansion/files/10717826/crash-2023-02-12_17.40.41-server.txt)

crash report trying to use tempad to tp directly to the nether

**Comment by A00826925** [comment]
![image](https://user-images.githubusercontent.com/73501467/218349923-3eb401ee-d679-4ba0-958d-729fbee90258.png)
i triewd to generate the nether using chunky, only to discover the entire dimension is missing as a whole

**Comment by A00826925** [comment]
[crash-2023-02-12_19.24.06-server.txt](https://github.com/infernalstudios/Infernal-Expansion/files/10717889/crash-2023-02-12_19.24.06-server.txt)
it broke level.dat when trying to reload the world with the mod on again

**Comment by A00826925** [comment]
I FIXED IT: removing infernal expansion and loading a world that previously had it will remove minecraft:the_nether from level.dat, you have to manually add it back into level.dat using nbtExplorer and copying a minecraft:the nether folder from another level.dat

**Comment by Dariensg** [comment]
This is the result of removing a biome adding mod, therefore invalidating the BiomeProvider for the nether. Typically, one should never remove a world generation changing mod after generating a world as issues as this can arise. This issue will not be fixed as it's mostly out of our power to control and should not be done in the first place.
