### ISSUE TITLE
Add config to customize mobs spawning in biomes

### ISSUE THREAD

**Issue by SomeCrbn** [nekomaster1000/Infernal-Expansion#47]
I looked through the server config in the world folder, and all it does is turn on and off existing features. I think it could be cool to allow adding biomes that the mobs can spawn in. This works nicely because then if people like me have biome mods, they can add biomes for the creatures to spawn in. This also could benefit modpack makers. I personally use oh the biomes you'll go and have a couple biomes I want to add to spawn listing.

**Comment by SwanX1** [comment]
This will be looked into in a future release
Until then you'll just have to wait :/

**Comment by Dariensg** [comment]
This is actually currently in the works for the next release, so you shouldn't have to wait too long!

**Comment by caelwarner** [comment]
I have to add (as I'm the one developing it), that there will be a system config and JSON files that will allow users to customize which biomes IE's mobs will spawn in, as well as spawnrates, minimum and maximum spawn counts for each biome.

**Comment by SomeCrbn** [comment]
Ok, sounds good. Also, is there a particular reason for the config to be in the world config vs the config folder? I imagine that placing it in the config folder could make this process potentially easier.

**Comment by Dariensg** [comment]
It is also being moved to the general config folder in the next release! Our config is getting a huge rework for this release, including a GUI

**Comment by SomeCrbn** [comment]
Oh awesome, thanks for letting me know :)
