### ISSUE TITLE
Glowdust Blocks Emit Darkness

### ISSUE THREAD

**Issue by Dayton-10** [nekomaster1000/Infernal-Expansion#6]
Glowdust blocks emit black around them, rather than light.
See [Original Discord omment](https://discord.com/channels/681976442220839008/795386070061023242/795470563992272916)

**Comment by CaelWarner** [comment]
![](https://cdn.discordapp.com/attachments/795386070061023242/795471230211063848/2021-01-03_20.58.16.png)

**Comment by CaelWarner** [comment]
The same happens with glimmering blackstone

**Comment by CaelWarner** [comment]
This is just how the Minecraft lighting engine works (see Crying Obsidian for an example). This only happens when brightness is set to something low. Possible ways to fix this are removing the light level from these blocks or making them emissive. However, the latter makes them glow at night.
