### ISSUE TITLE
Skeletal Piglin arm model issue

### ISSUE THREAD

**Issue by RedrixTTV** [nekomaster1000/Infernal-Expansion#75]
skeletal piglin's right arm is not in the right place 1 pixel inside its body or so
should be 1 pixel further out

screenshot of issue
![skeletal pig](https://user-images.githubusercontent.com/83433268/116628544-43312b00-a947-11eb-9477-286e7d932772.png)

this is fore the pre-release of infernal (I built the jar file from github)

**Comment by Dariensg** [comment]
Thanks for pointing this out! I had to adjust the model files by hand when making some changes and must've messed up by a pixel or two! We will get this fixed before final release!
