### ISSUE TITLE
Fire charges backfiring

### ISSUE THREAD

**Issue by keyberries** [nekomaster1000/Infernal-Expansion#94]
Fire charges hit the player who threw it if they move in the same direction as the charge, which I presume is because they don't have a LeftOwner tag like arrows, snowballs, and other vanilla projectiles do.

![image](https://user-images.githubusercontent.com/81661263/116900542-d9df3f80-ac06-11eb-8c5c-8dae02e84363.png)

**To reproduce**
Throw a fire charge while moving in the direction you throw it.

**Version Information**
 - Mod Version: 1725bc6
 - Minecraft Version: 1.16.5
 - Forge Version: 1.16.5-36.1.4
 - Other mods that were running when the crash happened: none

**Comment by Dariensg** [comment]
Fixed by PR #95
