### ISSUE TITLE
Incorrectly Labeled Smooth Dullstone Pressure Plates

### ISSUE THREAD

**Issue by keyberries** [nekomaster1000/Infernal-Expansion#98]
![image](https://user-images.githubusercontent.com/81661263/116924967-8e3c8e00-ac26-11eb-92d9-894862eddae9.png)

Not very important rn, but should def be fixed sooner than later

**Comment by SwanX1** [comment]
Not incorrectly labeled, it's supposed to glow up when stepped on

**Comment by keyberries** [comment]
ah, makes sense
